=== EriJan/Earthdawn-Character-Editor/config/charsheettemplate.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/charsheettemplate" xmlns="http://earthdawn.com/charsheettemplate" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="charsheettemplatetalent_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Name"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Action"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Strain"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Karma"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Attribute"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="AttributeStep"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Rank"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Step"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Dice"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Page"/>
		</xs:sequence>
		<xs:attribute type="xs:boolean" default="0" name="discipline"/>
		<xs:attribute type="xs:boolean" default="0" name="free"/>
		<xs:attribute type="xs:boolean" default="0" name="other"/>
		<xs:attribute type="xs:boolean" default="0" name="versatility"/>
	</xs:complexType>
	<xs:complexType name="charsheettemplatedisciplinebonus_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Circle"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Ability"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="charsheettemplatespell_type">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Name"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Circle"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Element"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Threads"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Weavingdifficulty"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Reattuningdifficulty"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Castingdifficulty"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Range"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Duration"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Effect"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Effectrarea"/>
			<xs:element  maxOccurs="1" minOccurs="0" type="xs:string" name="Bookref"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="charsheettemplateboolean_type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="truevalue" type="xs:string" default="Yes"/>
				<xs:attribute name="falsevalue" type="xs:string" default="No"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="CHARSHEETTEMPLATE">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="CurrentDateTime" type="xs:string"/>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="DisciplineName" type="xs:string"/>
				<xs:element name="DisciplineCircle" type="xs:string"/>
				<xs:element name="Race" type="xs:string"/>
				<xs:element name="Age" type="xs:string"/>
				<xs:element name="Eyes" type="xs:string"/>
				<xs:element name="Gender" type="xs:string"/>
				<xs:element name="Hair" type="xs:string"/>
				<xs:element name="Height" type="xs:string"/>
				<xs:element name="Skin" type="xs:string"/>
				<xs:element name="Weight" type="xs:string"/>
				<xs:element name="Passion" type="xs:string"/>
				<xs:element name="Player" type="xs:string"/>
				<xs:element name="AttributeBaseDex" type="xs:string"/>
				<xs:element name="AttributeBaseStr" type="xs:string"/>
				<xs:element name="AttributeBaseTou" type="xs:string"/>
				<xs:element name="AttributeBasePer" type="xs:string"/>
				<xs:element name="AttributeBaseWil" type="xs:string"/>
				<xs:element name="AttributeBaseCha" type="xs:string"/>
				<xs:element name="AttributeCurrentDex" type="xs:string"/>
				<xs:element name="AttributeCurrentStr" type="xs:string"/>
				<xs:element name="AttributeCurrentTou" type="xs:string"/>
				<xs:element name="AttributeCurrentPer" type="xs:string"/>
				<xs:element name="AttributeCurrentWil" type="xs:string"/>
				<xs:element name="AttributeCurrentCha" type="xs:string"/>
				<xs:element name="AttributeStepDex" type="xs:string"/>
				<xs:element name="AttributeStepStr" type="xs:string"/>
				<xs:element name="AttributeStepTou" type="xs:string"/>
				<xs:element name="AttributeStepPer" type="xs:string"/>
				<xs:element name="AttributeStepWil" type="xs:string"/>
				<xs:element name="AttributeStepCha" type="xs:string"/>
				<xs:element name="AttributeDiceDex" type="xs:string"/>
				<xs:element name="AttributeDiceStr" type="xs:string"/>
				<xs:element name="AttributeDiceTou" type="xs:string"/>
				<xs:element name="AttributeDicePer" type="xs:string"/>
				<xs:element name="AttributeDiceWil" type="xs:string"/>
				<xs:element name="AttributeDiceCha" type="xs:string"/>
				<xs:element name="LpincreaseDex" type="charsheettemplateboolean_type"/>
				<xs:element name="LpincreaseStr" type="charsheettemplateboolean_type"/>
				<xs:element name="LpincreaseTou" type="charsheettemplateboolean_type"/>
				<xs:element name="LpincreasePer" type="charsheettemplateboolean_type"/>
				<xs:element name="LpincreaseWil" type="charsheettemplateboolean_type"/>
				<xs:element name="LpincreaseCha" type="charsheettemplateboolean_type"/>
				<xs:element name="DefencePhysical" type="xs:string"/>
				<xs:element name="DefenceSocial" type="xs:string"/>
				<xs:element name="DefenceMystic" type="xs:string"/>
				<xs:element name="DeathAdjustment" type="xs:string"/>
				<xs:element name="DeathBase" type="xs:string"/>
				<xs:element name="DeathValue" type="xs:string"/>
				<xs:element name="UnconsciousnessAdjustment" type="xs:string"/>
				<xs:element name="UnconsciousnessBase" type="xs:string"/>
				<xs:element name="UnconsciousnessValue" type="xs:string"/>
				<xs:element name="RecoveryStep" type="xs:string"/>
				<xs:element name="RecoveryDice" type="xs:string"/>
				<xs:element name="RecoveryTestsperday" type="xs:string"/>
				<xs:element name="WoundThreshold" type="xs:string"/>
				<xs:element name="BloodWound" type="xs:string"/>
				<xs:element name="BloodDamage" type="xs:string"/>
				<xs:element name="LegendPointsTotal" type="xs:string"/>
				<xs:element name="LegendPointsCurrent" type="xs:string"/>
				<xs:element name="LegendPointsRenown" type="xs:string"/>
				<xs:element name="LegendPointsReputation" type="xs:string"/>
				<xs:element name="InitiativeBase" type="xs:string"/>
				<xs:element name="InitiativeDice" type="xs:string"/>
				<xs:element name="InitiativeStep" type="xs:string"/>
				<xs:element name="Talent" type="charsheettemplatetalent_type"/>
				<xs:element name="Skill" type="charsheettemplatetalent_type"/>
				<xs:element name="HealthDamage" type="xs:string"/>
				<xs:element name="KarmaBase" type="xs:string"/>
				<xs:element name="KarmaCurrent" type="xs:string"/>
				<xs:element name="KarmaMax" type="xs:string"/>
				<xs:element name="Movement" type="xs:string"/>
				<xs:element name="Carrying" type="xs:string"/>
				<xs:element name="ArmorMystic" type="xs:string"/>
				<xs:element name="ArmorPhysical" type="xs:string"/>
				<xs:element name="ShieldMystic" type="xs:string"/>
				<xs:element name="ShieldPhysical" type="xs:string"/>
				<xs:element name="ArmorPenalty" type="xs:string"/>
				<xs:element name="ArmorName" type="xs:string"/>
				<xs:element name="ArmorPenalties" type="xs:string"/>
				<xs:element name="DisciplineBonus" type="charsheettemplatedisciplinebonus_type"/>
				<xs:element name="WeaponName" type="xs:string"/>
				<xs:element name="WeaponDamagestep" type="xs:string"/>
				<xs:element name="WeaponSize" type="xs:string"/>
				<xs:element name="WeaponTimesforged" type="xs:string"/>
				<xs:element name="WeaponShortrange" type="xs:string"/>
				<xs:element name="WeaponLongrange" type="xs:string"/>
				<xs:element name="WeaponAttackstep" type="xs:string"/>
				<xs:element name="WeaponAttribute" type="xs:string"/>
				<xs:element name="WeaponStep" type="xs:string"/>
				<xs:element name="WeaponDice" type="xs:string"/>
				<xs:element name="InventoryDescription" type="xs:string"/>
				<xs:element name="InventoryWeight" type="xs:string"/>
				<xs:element name="Spell" type="charsheettemplatespell_type"/>
			</xs:choice>
			<xs:attribute name="menuentryname" type="xs:string" use="required"/>
			<xs:attribute name="filename" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/templates/ed4_character_sheet_ulisses_ext.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CHARSHEETTEMPLATE menuentryname="ED4 Ulisses Char" filename="ed4_character_sheet_ulisses_ext.pdf" xmlns="http://earthdawn.com/charsheettemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/charsheettemplate ../config/charsheettemplate.xsd">
	<CurrentDateTime>Zeitstempel</CurrentDateTime>
	<Name>Name</Name>
	<Race>Rasse</Race>
	<Age>Alter</Age>
	<Eyes>Augenfarbe</Eyes>
	<Gender>Geschlecht</Gender>
	<Hair>Haarfarbe</Hair>
	<Height>Groesse</Height>
	<Skin>Hautfarbe</Skin>
	<Weight>Gewicht</Weight>
	<Passion></Passion>
	<Player></Player>
	<DisciplineName>Disziplin</DisciplineName>
	<DisciplineCircle>Kreis</DisciplineCircle>
	<AttributeBaseDex></AttributeBaseDex>
	<AttributeBaseStr></AttributeBaseStr>
	<AttributeBaseTou></AttributeBaseTou>
	<AttributeBasePer></AttributeBasePer>
	<AttributeBaseWil></AttributeBaseWil>
	<AttributeBaseCha></AttributeBaseCha>
	<AttributeCurrentDex>Geschicklichkeit</AttributeCurrentDex>
	<AttributeCurrentStr>Staerke</AttributeCurrentStr>
	<AttributeCurrentTou>Zaehigkeit</AttributeCurrentTou>
	<AttributeCurrentPer>Warnehmung</AttributeCurrentPer>
	<AttributeCurrentWil>Willenskraft</AttributeCurrentWil>
	<AttributeCurrentCha>Charisma</AttributeCurrentCha>
	<AttributeStepDex>Stufe 1</AttributeStepDex>
	<AttributeStepStr>Stufe 2</AttributeStepStr>
	<AttributeStepTou>Stufe 3</AttributeStepTou>
	<AttributeStepPer>Stufe 4</AttributeStepPer>
	<AttributeStepWil>Stufe 5</AttributeStepWil>
	<AttributeStepCha>Stufe 6</AttributeStepCha>
	<AttributeDiceDex>W rfel 1</AttributeDiceDex>
	<AttributeDiceStr>W rfel 2</AttributeDiceStr>
	<AttributeDiceTou>W rfel 3</AttributeDiceTou>
	<AttributeDicePer>W rfel 4</AttributeDicePer>
	<AttributeDiceWil>W rfel 5</AttributeDiceWil>
	<AttributeDiceCha>W rfel 6</AttributeDiceCha>
	<LpincreaseDex truevalue="Ja" falsevalue="Off">Check Box1</LpincreaseDex>
	<LpincreaseDex truevalue="Ja" falsevalue="Off">Check Box11</LpincreaseDex>
	<LpincreaseDex truevalue="Ja" falsevalue="Off">Check Box12</LpincreaseDex>
	<LpincreaseStr truevalue="Ja" falsevalue="Off">Check Box2</LpincreaseStr>
	<LpincreaseStr truevalue="Ja" falsevalue="Off">Check Box22</LpincreaseStr>
	<LpincreaseStr truevalue="Ja" falsevalue="Off">Check Box23</LpincreaseStr>
	<LpincreaseTou truevalue="Ja" falsevalue="Off">Check Box31</LpincreaseTou>
	<LpincreaseTou truevalue="Ja" falsevalue="Off">Check Box32</LpincreaseTou>
	<LpincreaseTou truevalue="Ja" falsevalue="Off">Check Box33</LpincreaseTou>
	<LpincreasePer truevalue="Ja" falsevalue="Off">Check Box41</LpincreasePer>
	<LpincreasePer truevalue="Ja" falsevalue="Off">Check Box42</LpincreasePer>
	<LpincreasePer truevalue="Ja" falsevalue="Off">Check Box43</LpincreasePer>
	<LpincreaseWil truevalue="Ja" falsevalue="Off">Check Box51</LpincreaseWil>
	<LpincreaseWil truevalue="Ja" falsevalue="Off">Check Box52</LpincreaseWil>
	<LpincreaseWil truevalue="Ja" falsevalue="Off">Check Box53</LpincreaseWil>
	<LpincreaseCha truevalue="Ja" falsevalue="Off">Check Box61</LpincreaseCha>
	<LpincreaseCha truevalue="Ja" falsevalue="Off">Check Box62</LpincreaseCha>
	<LpincreaseCha truevalue="Ja" falsevalue="Off">Check Box63</LpincreaseCha>
	<DefencePhysical>KV</DefencePhysical>
	<DefenceMystic>MV</DefenceMystic>
	<DefenceSocial>SV</DefenceSocial>
	<DeathAdjustment></DeathAdjustment>
	<DeathBase></DeathBase>
	<DeathValue>Todesschwelle</DeathValue>
	<UnconsciousnessAdjustment></UnconsciousnessAdjustment>
	<UnconsciousnessBase></UnconsciousnessBase>
	<UnconsciousnessValue>Bewusstlosigkeitsschwelle</UnconsciousnessValue>
	<RecoveryStep></RecoveryStep>
	<RecoveryDice>WÃ¼rfel</RecoveryDice>
	<RecoveryTestsperday>Erholungsproben/&gt;Tag</RecoveryTestsperday>
	<WoundThreshold>Wundschwelle</WoundThreshold>
	<BloodWound></BloodWound>
	<BloodDamage>Blutschaden</BloodDamage>
	<LegendPointsTotal>Gesamt</LegendPointsTotal>
	<LegendPointsCurrent>Aktuell</LegendPointsCurrent>
	<LegendPointsRenown>Ruhm</LegendPointsRenown>
	<LegendPointsReputation>Ruf</LegendPointsReputation>
	<InitiativeBase>Geschick</InitiativeBase>
	<InitiativeDice></InitiativeDice>
	<InitiativeStep>Modifizierte</InitiativeStep>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.0</Name><Action>Text5.0.0</Action><Strain>Text5.0.1</Strain><Attribute>Text4.0.1</Attribute><AttributeStep>Text4.0.2</AttributeStep><Rank>Text4.0.0</Rank><Step>Text4.0.2</Step><Dice>Text4.0.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.1</Name><Action>Text5.1.0</Action><Strain>Text5.1.1</Strain><Attribute>Text4.1.1</Attribute><AttributeStep>Text4.1.2</AttributeStep><Rank>Text4.1.0</Rank><Step>Text4.1.2</Step><Dice>Text4.1.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.2</Name><Action>Text5.2.0</Action><Strain>Text5.2.1</Strain><Attribute>Text4.2.1</Attribute><AttributeStep>Text4.2.2</AttributeStep><Rank>Text4.2.0</Rank><Step>Text4.2.2</Step><Dice>Text4.2.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.3</Name><Action>Text5.3.0</Action><Strain>Text5.3.1</Strain><Attribute>Text4.3.1</Attribute><AttributeStep>Text4.3.2</AttributeStep><Rank>Text4.3.0</Rank><Step>Text4.3.2</Step><Dice>Text4.3.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.4</Name><Action>Text5.4.0</Action><Strain>Text5.4.1</Strain><Attribute>Text4.4.1</Attribute><AttributeStep>Text4.4.2</AttributeStep><Rank>Text4.4.0</Rank><Step>Text4.4.2</Step><Dice>Text4.4.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.5</Name><Action>Text5.5.0</Action><Strain>Text5.5.1</Strain><Attribute>Text4.5.1</Attribute><AttributeStep>Text4.5.2</AttributeStep><Rank>Text4.5.0</Rank><Step>Text4.5.2</Step><Dice>Text4.5.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.6</Name><Action>Text5.6.0</Action><Strain>Text5.6.1</Strain><Attribute>Text4.6.1</Attribute><AttributeStep>Text4.6.2</AttributeStep><Rank>Text4.6.0</Rank><Step>Text4.6.2</Step><Dice>Text4.6.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.7</Name><Action>Text5.7.0</Action><Strain>Text5.7.1</Strain><Attribute>Text4.7.1</Attribute><AttributeStep>Text4.7.2</AttributeStep><Rank>Text4.7.0</Rank><Step>Text4.7.2</Step><Dice>Text4.7.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.8</Name><Action>Text5.8.0</Action><Strain>Text5.8.1</Strain><Attribute>Text4.8.1</Attribute><AttributeStep>Text4.8.2</AttributeStep><Rank>Text4.8.0</Rank><Step>Text4.8.2</Step><Dice>Text4.8.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.9</Name><Action>Text5.9.0</Action><Strain>Text5.9.1</Strain><Attribute>Text4.9.1</Attribute><AttributeStep>Text4.9.2</AttributeStep><Rank>Text4.9.0</Rank><Step>Text4.9.2</Step><Dice>Text4.9.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.10</Name><Action>Text5.10.0</Action><Strain>Text5.10.1</Strain><Attribute>Text4.10.1</Attribute><AttributeStep>Text4.10.2</AttributeStep><Rank>Text4.10.0</Rank><Step>Text4.10.2</Step><Dice>Text4.10.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.11</Name><Action>Text5.11.0</Action><Strain>Text5.11.1</Strain><Attribute>Text4.11.1</Attribute><AttributeStep>Text4.11.2</AttributeStep><Rank>Text4.11.0</Rank><Step>Text4.11.2</Step><Dice>Text4.11.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.12</Name><Action>Text5.12.0</Action><Strain>Text5.12.1</Strain><Attribute>Text4.12.1</Attribute><AttributeStep>Text4.12.2</AttributeStep><Rank>Text4.12.0</Rank><Step>Text4.12.2</Step><Dice>Text4.12.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.13</Name><Action>Text5.13.0</Action><Strain>Text5.13.1</Strain><Attribute>Text4.13.1</Attribute><AttributeStep>Text4.13.2</AttributeStep><Rank>Text4.13.0</Rank><Step>Text4.13.2</Step><Dice>Text4.13.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.14</Name><Action>Text5.14.0</Action><Strain>Text5.14.1</Strain><Attribute>Text4.14.1</Attribute><AttributeStep>Text4.14.2</AttributeStep><Rank>Text4.14.0</Rank><Step>Text4.14.2</Step><Dice>Text4.14.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.15</Name><Action>Text5.15.0</Action><Strain>Text5.15.1</Strain><Attribute>Text4.15.1</Attribute><AttributeStep>Text4.15.2</AttributeStep><Rank>Text4.15.0</Rank><Step>Text4.15.2</Step><Dice>Text4.15.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.16</Name><Action>Text5.16.0</Action><Strain>Text5.16.1</Strain><Attribute>Text4.16.1</Attribute><AttributeStep>Text4.16.2</AttributeStep><Rank>Text4.16.0</Rank><Step>Text4.16.2</Step><Dice>Text4.16.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.17</Name><Action>Text5.17.0</Action><Strain>Text5.17.1</Strain><Attribute>Text4.17.1</Attribute><AttributeStep>Text4.17.2</AttributeStep><Rank>Text4.17.0</Rank><Step>Text4.17.2</Step><Dice>Text4.17.3</Dice><Page></Page></Talent>
	<Talent discipline="1" free="0" other="0" versatility="0"><Name>Text3.18</Name><Action>Text5.18.0</Action><Strain>Text5.18.1</Strain><Attribute>Text4.18.1</Attribute><AttributeStep>Text4.18.2</AttributeStep><Rank>Text4.18.0</Rank><Step>Text4.18.2</Step><Dice>Text4.18.3</Dice><Page></Page></Talent>
