=== EriJan/Earthdawn-Character-Editor/config/earthdawncharakter.xsd
<?xml version="1.0" encoding="ISO-8859-15"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://earthdawn.de" targetNamespace="http://earthdawn.de" elementFormDefault="qualified">
	<xs:simpleType name="ATTRIBUT_name_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Charisma"/>
			<xs:enumeration value="Geschicklichkeit"/>
			<xs:enumeration value="Stärke"/>
			<xs:enumeration value="Wahrnehmung"/>
			<xs:enumeration value="Willenskraft"/>
			<xs:enumeration value="Zähigkeit"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="plusminus_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="+"/>
			<xs:enumeration value="-"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="janein_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="j"/>
			<xs:enumeration value="n"/>
			<xs:enumeration value="-"/>
			<xs:enumeration value="*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="geschlecht_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="m"/>
			<xs:enumeration value="w"/>
			<xs:enumeration value="-"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="disziplinlist_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Alchemist"/>
			<xs:enumeration value="Assasine"/>
			<xs:enumeration value="Dieb"/>
			<xs:enumeration value="Elementarist"/>
			<xs:enumeration value="Illusionist"/>
			<xs:enumeration value="Krieger"/>
			<xs:enumeration value="Läuterer"/>
			<xs:enumeration value="Luftpirat"/>
			<xs:enumeration value="Magier"/>
			<xs:enumeration value="OldWalker"/>
			<xs:enumeration value="Schütze"/>
			<xs:enumeration value="Schwertmeister"/>
			<xs:enumeration value="Steppenreiter"/>
			<xs:enumeration value="Windmeister"/>
			<xs:enumeration value="Windscout"/>
			<xs:enumeration value="NichtAdept"/>
			<xs:enumeration value="Schamane"/>
			<xs:enumeration value="Tiermeister"/>
			<xs:enumeration value="Geisterbeschwörer"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ATTRIBUT_type">
		<xs:attribute name="name" type="ATTRIBUT_name_type" use="required"/>
		<xs:attribute name="steig" type="xs:integer" use="required"/>
		<xs:attribute name="wert" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="GEGENSTAND_type">
		<xs:attribute name="bezeichnung" type="xs:string" use="required"/>
		<xs:attribute name="gewicht" type="xs:decimal" use="required"/>
	</xs:complexType>
	<xs:complexType name="AUSRUESTUNG_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="GEGENSTAND" type="GEGENSTAND_type" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="ort" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="BEWEGEN_type">
		<xs:attribute name="flug_kampf" type="xs:integer" use="required"/>
		<xs:attribute name="flug_normal" type="xs:integer" use="required"/>
		<xs:attribute name="laufen_kampf" type="xs:integer" use="required"/>
		<xs:attribute name="laufen_normal" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="DISZIPLIN_type">
		<xs:attribute name="Kreis" type="xs:integer" use="required"/>
		<xs:attribute name="bezeichnung" type="disziplinlist_type" use="required"/>
		<xs:attribute name="nr" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="GELD_type">
		<xs:attribute name="ort" type="xs:string" use="optional" default="selbst"/>
		<xs:attribute name="Kupfer" type="xs:integer"/>
		<xs:attribute name="Silber" type="xs:integer"/>
		<xs:attribute name="Gold" type="xs:integer"/>
		<xs:attribute name="Erde" type="xs:integer"/>
		<xs:attribute name="Wasser" type="xs:integer"/>
		<xs:attribute name="Feuer" type="xs:integer"/>
		<xs:attribute name="Luft" type="xs:integer"/>
		<xs:attribute name="Orichalcum" type="xs:integer"/>
	</xs:complexType>
	<xs:complexType name="GEWICHT_type">
		<xs:attribute name="hebelimit" type="xs:integer"/>
		<xs:attribute name="traglast" type="xs:integer"/>
	</xs:complexType>
	<xs:complexType name="INITIATIVE_type">
		<xs:attribute name="wert" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="KARMA_type">
		<xs:attribute name="aktuell" type="xs:integer" use="required"/>
		<xs:attribute name="kosten" type="xs:integer" use="required"/>
		<xs:attribute name="max" type="xs:integer" use="required"/>
		<xs:attribute name="stufe" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="LP_type">
		<xs:attribute name="bemerkung" type="xs:string" use="required"/>
		<xs:attribute name="lp" type="xs:integer" use="required"/>
		<xs:attribute name="typ" type="plusminus_type" use="required"/>
		<xs:attribute name="zeit" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="LEGENDENPUNKTE_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="LP" type="LP_type" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="RUESTUNG_type">
		<xs:attribute name="bezeichnung" type="xs:string" use="required"/>
		<xs:attribute name="gewicht" type="xs:decimal" use="required"/>
		<xs:attribute name="aktiv" type="janein_type" use="required"/>
		<xs:attribute name="behinderung" type="xs:integer" use="required"/>
		<xs:attribute name="bruchschwelle" type="xs:integer" use="required"/>
		<xs:attribute name="mystisch" type="xs:integer" use="required"/>
		<xs:attribute name="physikalisch" type="xs:integer" use="required"/>
		<xs:attribute name="ort" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SCHADEN_type">
		<xs:attribute name="blut" type="xs:integer" use="required"/>
		<xs:attribute name="schaden" type="xs:integer" use="required"/>
		<xs:attribute name="wunden" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="FERTIGKEIT_type">
		<xs:attribute name="aktion" type="janein_type" use="required"/>
		<xs:attribute name="attributstufe" type="xs:integer" use="required"/>
		<xs:attribute name="bezeichnung" type="xs:string" use="required"/>
		<xs:attribute name="rang" type="xs:integer" use="required"/>
		<xs:attribute name="ueberanstrengung" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="TALENT_type">
		<xs:complexContent>
			<xs:extension base="FERTIGKEIT_type">
				<xs:attribute name="karma" type="janein_type" use="required"/>
				<xs:attribute name="disziplintalent" type="janein_type" use="required"/>
				<xs:attribute name="kreis" type="xs:integer" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="TALENTE_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="TALENT" type="TALENT_type" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="disziplin" type="disziplinlist_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="FERTIGKEITEN_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="FERTIGKEIT" type="FERTIGKEIT_type" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="TOD_type">
		<xs:attribute name="bewustlschwelle" type="xs:integer" use="required"/>
		<xs:attribute name="erholproben" type="xs:integer" use="required"/>
		<xs:attribute name="todschwelle" type="xs:integer" use="required"/>
		<xs:attribute name="verwundschwelle" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="WAFFE_type">
		<xs:attribute name="bezeichnung" type="xs:string" use="required"/>
		<xs:attribute name="gewicht" type="xs:decimal" use="required"/>
		<xs:attribute name="mittel" type="xs:integer" use="required"/>
		<xs:attribute name="nah" type="xs:integer" use="required"/>
		<xs:attribute name="ort" type="xs:string" use="required"/>
		<xs:attribute name="schaden" type="xs:integer" use="required"/>
		<xs:attribute name="weit" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="WAFFEN_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="WAFFE" type="WAFFE_type" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="WIDERSTANDSKRAFT_type">
		<xs:attribute name="körperlich" type="xs:integer" use="required"/>
		<xs:attribute name="magisch" type="xs:integer" use="required"/>
		<xs:attribute name="sozial" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="ZAUBER_type">
		<xs:attribute name="bezeichnung" type="xs:string" use="required"/>
		<xs:attribute name="effekt" type="xs:string" use="required"/>
		<xs:attribute name="faeden" type="xs:integer" use="required"/>
		<xs:attribute name="kreis" type="xs:integer" use="required"/>
		<xs:attribute name="reichweite" type="xs:string" use="required"/>
		<xs:attribute name="webschwierigkeit" type="xs:string" use="required"/>
		<xs:attribute name="wirkschwierigkeit" type="xs:string" use="required"/>
		<xs:attribute name="wirkungsdauer" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ZAUBERLISTE_type">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="ZAUBER" type="ZAUBER_type" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="disziplin" type="disziplinlist_type" use="required"/>
	</xs:complexType>
	<xs:element name="EDCHARAKTER">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="ATTRIBUT" type="ATTRIBUT_type" maxOccurs="unbounded"/>
				<xs:element name="AUSRUESTUNG" type="AUSRUESTUNG_type" maxOccurs="unbounded"/>
				<xs:element name="BEMERKUNG" type="xs:string"/>
				<xs:element name="BEWEGEN" type="BEWEGEN_type"/>
				<xs:element name="DISZIPLIN" type="DISZIPLIN_type" maxOccurs="3"/>
				<xs:element name="FERTIGKEITEN" type="FERTIGKEITEN_type" maxOccurs="unbounded"/>
				<xs:element name="GELD" type="GELD_type" maxOccurs="unbounded"/>
				<xs:element name="GEWICHT" type="GEWICHT_type"/>
				<xs:element name="INITIATIVE" type="INITIATIVE_type"/>
				<xs:element name="KARMA" type="KARMA_type"/>
				<xs:element name="LEGENDENPUNKTE" type="LEGENDENPUNKTE_type"/>
				<xs:element name="RUESTUNG" type="RUESTUNG_type" maxOccurs="unbounded"/>
				<xs:element name="SCHADEN" type="SCHADEN_type"/>
				<xs:element name="TALENTE" type="TALENTE_type" maxOccurs="unbounded"/>
				<xs:element name="TOD" type="TOD_type"/>
				<xs:element name="WAFFEN" type="WAFFEN_type" maxOccurs="unbounded"/>
				<xs:element name="WIDERSTANDSKRAFT" type="WIDERSTANDSKRAFT_type"/>
				<xs:element name="ZAUBERLISTE" type="ZAUBERLISTE_type" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="Alter" type="xs:integer" use="required"/>
			<xs:attribute name="Augenf" type="xs:string" use="required"/>
			<xs:attribute name="Geschlecht" type="geschlecht_type" use="required"/>
			<xs:attribute name="Gewicht" type="xs:integer" use="required"/>
			<xs:attribute name="Groesse" type="xs:integer" use="required"/>
			<xs:attribute name="Haarf" type="xs:string" use="required"/>
			<xs:attribute name="Hautf" type="xs:string" use="required"/>
			<xs:attribute name="Rasse" type="xs:string" use="required"/>
			<xs:attribute name="bezeichnung" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/examples/hugo.xml
<EDCHARAKTER Alter="100" Augenf="?" Geschlecht="w" Gewicht="50" Groesse="20" Haarf="?" Hautf="?" Rasse="Obsidianer" bezeichnung="Hugo" xmlns="http://earthdawn.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.de earthdawncharakter.xsd">
  <ATTRIBUT name="Charisma" steig="0" wert="1"/>
  <ATTRIBUT name="Geschicklichkeit" steig="2" wert="17"/>
  <ATTRIBUT name="Stärke" steig="0" wert="21"/>
  <ATTRIBUT name="Wahrnehmung" steig="0" wert="3"/>
  <ATTRIBUT name="Willenskraft" steig="0" wert="13"/>
  <ATTRIBUT name="Zähigkeit" steig="2" wert="19"/>
  <AUSRUESTUNG ort="selbst">
    <GEGENSTAND bezeichnung="" gewicht="0"/>
  </AUSRUESTUNG>
  <BEMERKUNG/>
  <BEWEGEN flug_kampf="0" flug_normal="0" laufen_kampf="33" laufen_normal="65"/>
  <DISZIPLIN Kreis="1" bezeichnung="Dieb" nr="1"/>
  <DISZIPLIN Kreis="0" bezeichnung="Schütze" nr="2"/>
  <FERTIGKEITEN>
    <FERTIGKEIT aktion="n" attributstufe="7" bezeichnung="Akrobatik" rang="5" ueberanstrengung="0"/>
  </FERTIGKEITEN>
  <GELD Erde="34" Feuer="234" Gold="1000" Kupfer="1" Luft="342" Orichalcum="2342" Silber="120" Wasser="234"/>
  <GEWICHT hebelimit="735" traglast="360"/>
  <INITIATIVE wert="7"/>
  <KARMA aktuell="11" kosten="10" max="20" stufe="3"/>
  <LEGENDENPUNKTE>
    <LP bemerkung="Karnickel erschlagen" lp="100" typ="-" zeit=""/>
    <LP bemerkung="" lp="0" typ="+" zeit=""/>
  </LEGENDENPUNKTE>
  <RUESTUNG aktiv="j" behinderung="0" bezeichnung="Natürliche Rüstung" bruchschwelle="0" gewicht="0" mystisch="1" ort="-" physikalisch="0"/>
  <SCHADEN blut="4" schaden="0" wunden="1"/>
  <TALENTE disziplin="Mensch">
    <TALENT aktion="-" attributstufe="0" bezeichnung="Vielseitigkeit" disziplintalent="n" karma="n" kreis="1" rang="2" ueberanstrengung="0"/>
  </TALENTE>
  <TALENTE disziplin="Dieb">
    <TALENT aktion="j" attributstufe="7" bezeichnung="Dietrich" disziplintalent="j" karma="n" kreis="1" rang="2" ueberanstrengung="0"/>
    <TALENT aktion="j" attributstufe="7" bezeichnung="Klettern" disziplintalent="n" karma="n" kreis="1" rang="1" ueberanstrengung="0"/>
    <TALENT aktion="n" attributstufe="7" bezeichnung="Lautloser Gang" disziplintalent="j" karma="n" kreis="1" rang="11" ueberanstrengung="0"/>
    <TALENT aktion="j" attributstufe="7" bezeichnung="Taschendiebstahl" disziplintalent="j" karma="n" kreis="1" rang="11" ueberanstrengung="0"/>
  </TALENTE>
  <TOD bewustlschwelle="35" erholproben="3" todschwelle="43" verwundschwelle="15"/>

  <WAFFEN>
    <WAFFE bezeichnung="Katapult" mittel="10000" nah="10000" schaden="20" weit="10000"/>
  </WAFFEN>
  <WIDERSTANDSKRAFT körperlich="9" magisch="3" sozial="2"/>
</EDCHARAKTER>
