=== EriJan/Earthdawn-Character-Editor/config/earthdawnitems.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/items" xmlns="http://earthdawn.com/items" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:element name="ITEMS">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="ARMOR" type="edt:ARMOR_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="SHIELD" type="edt:SHIELD_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="WEAPON" type="edt:WEAPON_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="AMMUNITION" type="edt:AMMUNITION_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="MAGICITEM" type="edt:MAGICITEM_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="PATTERNITEM" type="edt:PATTERNITEM_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="BLOODCHARMITEM" type="edt:BLOODCHARMITEM_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="THREADITEM" type="edt:THREADITEM_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="ITEM" type="edt:ITEM_type"/>
			</xs:sequence>
			<xs:attribute name="lang" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/config/itemstore/PlayersGuideED3_Shields.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ITEMS lang="en" xmlns="http://earthdawn.com/items" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/items ../earthdawnitems.xsd">
	<RULESETCONSTRAINT>ED3</RULESETCONSTRAINT>		
<!--  Shield vollstÃ¤ndig PG	-->
	<SHIELD kind="shield" name="Bark"            physicalarmor="2" mysticarmor="1" penalty="1" physicaldeflectionbonus="2" mysticdeflectionbonus="1" shatterthreshold="14" edn="11" weight="5"  price="15"  bookref="PG p.257"/>
	<SHIELD kind="shield" name="Body"            physicalarmor="5" mysticarmor="0" penalty="2" physicaldeflectionbonus="4" mysticdeflectionbonus="0" shatterthreshold="21"          weight="15" price="50"  bookref="PG p.257"/>
	<SHIELD kind="shield" name="Buckler"         physicalarmor="1" mysticarmor="0" penalty="0" physicaldeflectionbonus="1" mysticdeflectionbonus="0" shatterthreshold="17"          weight="3"  price="5"   bookref="PG p.257"/>
	<SHIELD kind="shield" name="Crystal Buckler" physicalarmor="1" mysticarmor="1" penalty="0" physicaldeflectionbonus="1" mysticdeflectionbonus="1" shatterthreshold="17" edn="10" weight="5"  price="50"  bookref="PG p.257"/>
	<SHIELD kind="shield" name="Crystal Raider"  physicalarmor="3" mysticarmor="3" penalty="2" physicaldeflectionbonus="3" mysticdeflectionbonus="3" shatterthreshold="18" edn="14" weight="15" price="150" bookref="PG p.257"/>
	<SHIELD kind="shield" name="Ferndask"        physicalarmor="1" mysticarmor="2" penalty="1" physicaldeflectionbonus="1" mysticdeflectionbonus="2" shatterthreshold="16" edn="11" weight="5"  price="22"  bookref="PG p.257"/>
	<SHIELD kind="shield" name="Footman's"       physicalarmor="3" mysticarmor="0" penalty="1" physicaldeflectionbonus="2" mysticdeflectionbonus="0" shatterthreshold="19"          weight="10" price="15"  bookref="PG p.257"/>
	<SHIELD kind="shield" name="Rider's"         physicalarmor="3" mysticarmor="0" penalty="1" physicaldeflectionbonus="2" mysticdeflectionbonus="0" shatterthreshold="19"          weight="8"  price="20"  bookref="PG p.257"/>
</ITEMS>

=== EriJan/Earthdawn-Character-Editor/config/itemstore/Spielerhandbuch.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ITEMS lang="de" xmlns="http://earthdawn.com/items" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/items ../earthdawnitems.xsd">
	<ARMOR kind="armor" name="Blutkiesel"                physicalarmor="5" mysticarmor="3" penalty="1" price="300"   weight="0"  bookref="SH S.261"/>
	<ARMOR kind="armor" name="Espagrasshuppen-Umhang"    physicalarmor="3" mysticarmor="1" penalty="0" price="200"   weight="10" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Farnrüstung"               physicalarmor="2" mysticarmor="3" penalty="0" price="125"   weight="15" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Fellrüstung"               physicalarmor="5" mysticarmor="1" penalty="1" price="50"    weight="25" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Gehärtete Lederrüstung"    physicalarmor="5" mysticarmor="0" penalty="1" price="40"    weight="20" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Gesteppte Lederrüstung"    physicalarmor="4" mysticarmor="0" penalty="0" price="20"    weight="20" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Gesteppte Tuchrüstung"     physicalarmor="2" mysticarmor="0" penalty="0" price="2"     weight="5"  bookref="SH S.261"/>
	<ARMOR kind="armor" name="Kettenrüstung"             physicalarmor="7" mysticarmor="0" penalty="3" price="180"   weight="40" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Kristallplattenrüstung"    physicalarmor="7" mysticarmor="7" penalty="5" price="12000" weight="90" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Kristallringrüstung"       physicalarmor="4" mysticarmor="4" penalty="2" price="500"   weight="45" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Lebendige Kristallrüstung" physicalarmor="6" mysticarmor="3" penalty="2" price="1100"  weight="0"  bookref="SH S.261"/>
	<ARMOR kind="armor" name="Lederrüstung"              physicalarmor="3" mysticarmor="0" penalty="0" price="10"    weight="15" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Obsidianerhaut"            physicalarmor="3" mysticarmor="1" penalty="0" price="100"   weight="20" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Plattenrüstung"            physicalarmor="9" mysticarmor="0" penalty="4" price="3000"  weight="60" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Ringrüstung"               physicalarmor="6" mysticarmor="0" penalty="2" price="110"   weight="30" bookref="SH S.261"/>
	<ARMOR kind="armor" name="Wyvernhaut"                physicalarmor="8" mysticarmor="1" penalty="3" price="2000"  weight="50" bookref="SH S.261"/>

	<WEAPON kind="throwing weapon" name="Bola"           damagestep="3" strengthmin="6" size="2" shortrange="12" longrange="24" price="10"  weight="2"     dexteritymin="9" bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Dolch"          damagestep="2" strengthmin="4" size="1" shortrange="10" longrange="20" price="0.8" weight="1"     bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Falkenklaue"    damagestep="4" strengthmin="8" size="3" shortrange="24" longrange="48" price="75"  weight="2"     bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Flugdolch"      damagestep="2" strengthmin="4" size="1" shortrange="20" longrange="40" price="25"  weight="0.75"  bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Messer"         damagestep="1" strengthmin="3" size="1" shortrange="8"  longrange="16" price="0.3" weight="0.625" bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Netz (leicht)"  damagestep="0" strengthmin="4" size="3" shortrange="6"  longrange="12" price="15"  weight="5"     bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Netz (mittel)"  damagestep="0" strengthmin="5" size="4" shortrange="6"  longrange="12" price="20"  weight="7"     bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Netz (groß)"    damagestep="0" strengthmin="7" size="5" shortrange="6"  longrange="12" price="25"  weight="10"    bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Netz (rießig)"  damagestep="0" strengthmin="8" size="6" shortrange="6"  longrange="12" price="40"  weight="12"    bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Speer"          damagestep="4" strengthmin="9" size="3" shortrange="10" longrange="20" price="9"   weight="3"     bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Windling Netz"  damagestep="0" strengthmin="3" size="2" shortrange="6"  longrange="12" price="15"  weight="0.75"  dexteritymin="9" bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Windling Speer" damagestep="2" strengthmin="4" size="1" shortrange="8"  longrange="16" price="25"  weight="0.5"   bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Wurfaxe"        damagestep="3" strengthmin="7" size="3" shortrange="12" longrange="24" price="25"  weight="2"     bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Wurfdolch"      damagestep="2" strengthmin="4" size="1" shortrange="16" longrange="32" price="2"   weight="0.75"  bookref="PG p.252"/>
	<WEAPON kind="throwing weapon" name="Wurfbeil"       damagestep="1" strengthmin="4" size="1" shortrange="18" longrange="36" price="0.3" weight="0.5"   bookref="PG p.252"/>
</ITEMS>
