=== EriJan/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="CIRCLENAME_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="DISZIPINABILITY_type">
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="TALENTABILITY_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="limitation" type="xs:string" default=""/>
	</xs:complexType>
	<xs:complexType name="KARMAABILITY_type">
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="spend" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="DEFENSEABILITY_type">
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="kind" type="edt:defensekind_type" default="physical"/>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element maxOccurs="unbounded" minOccurs="0" name="DISZIPLINETALENT" type="TALENTABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="OPTIONALTALENT" type="TALENTABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="KARMA" type="KARMAABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="ABILITY" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="DEFENSE" type="DEFENSEABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="INITIATIVE" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="RECOVERYTEST" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="KARMASTEP" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="SPELL" type="DISZIPINABILITY_type"/>
			</xs:choice>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/config/disciplines/Warrior.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<DISCIPLINE  name="Warrior" lang="en" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../earthdawndiscipline.xsd">
	<OPTIONALTALENT name="Acrobatic Strike" circle="1"/>
	<OPTIONALTALENT name="Air Dance" circle="1"/>
	<OPTIONALTALENT name="Climbing" circle="1"/>
	<OPTIONALTALENT name="Maneuver" circle="1"/>
	<OPTIONALTALENT name="Parry" circle="1"/>
	<DISZIPLINETALENT name="Avoid Blow" circle="1"/>
	<DISZIPLINETALENT name="Karma Ritual" circle="1"/>
	<DISZIPLINETALENT name="Melee Weapons" circle="1"/>
	<DISZIPLINETALENT name="Unarmed Combat" circle="1"/>
	<DISZIPLINETALENT name="Wood Skin" circle="1"/>
	<OPTIONALTALENT name="Detect Weapon" circle="2"/>
	<OPTIONALTALENT name="Durability" circle="2" limitation="9/7"/>
	<OPTIONALTALENT name="Fireblood" circle="2"/>
	<OPTIONALTALENT name="Heartening Laugh" circle="2"/>
	<OPTIONALTALENT name="Missile Weapons" circle="2"/>
	<OPTIONALTALENT name="Swift Kick" circle="2"/>
	<OPTIONALTALENT name="Throwing Weapons" circle="2"/>
	<OPTIONALTALENT name="Tiger Spring" circle="2"/>
	<DEFENSE kind="physical" circle="2"/>
	<DISZIPLINETALENT name="Anticipate Blow" circle="2"/>
	<DISZIPLINETALENT name="Wound Balance" circle="3"/>
	<KARMA spend="Strength-only Test" circle="4"/>
	<DISZIPLINETALENT name="Thread Weaving" circle="4" limitation="War Weaving"/>
	<OPTIONALTALENT name="Cobra Strike" circle="5"/>
	<OPTIONALTALENT name="Disarm" circle="5"/>
	<OPTIONALTALENT name="Leadership" circle="5"/>
	<OPTIONALTALENT name="Lion Heart" circle="5"/>
	<OPTIONALTALENT name="Second Weapon" circle="5"/>
	<OPTIONALTALENT name="Shield Charge" circle="5"/>
	<OPTIONALTALENT name="Steel Stare" circle="5"/>
	<OPTIONALTALENT name="Tactics" circle="5"/>
	<ABILITY name="Batte Rites" circle="5"/>
	<DISZIPLINETALENT name="Temper Self" circle="5"/>
	<KARMA spend="Dexterity-ony Test" circle="6"/>
	<DISZIPLINETALENT name="Life Check" circle="6"/>
	<KARMA spend="close combat Damage Test" circle="7"/>
	<DISZIPLINETALENT name="Crushing Blow" circle="7"/>
	<DEFENSE kind="physical" circle="8"/>
	<DISZIPLINETALENT name="Second Attack" circle="8"/>
	<OPTIONALTALENT name="Battle Bellow" circle="9"/>
	<OPTIONALTALENT name="Body Blade" circle="9"/>
	<OPTIONALTALENT name="Critical Hit" circle="9"/>
	<OPTIONALTALENT name="Frenzy" circle="9"/>
	<OPTIONALTALENT name="Matrix Strike" circle="9"/>
	<OPTIONALTALENT name="Shield Beater" circle="9"/>
	<OPTIONALTALENT name="Spirit Strike" circle="9"/>
	<OPTIONALTALENT name="Steel Thought" circle="9"/>
	<ABILITY name="Battlefield Awareness" circle="9"/>
	<KARMA spend="Recovery Test" circle="9"/>
	<DISZIPLINETALENT name="Earth Skin" circle="9"/>
	<DEFENSE kind="physical" circle="10"/>
	<KARMA spend="Willpower-only Test" circle="10"/>
	<DISZIPLINETALENT name="Resist Pain" circle="10"/>
	<DEFENSE kind="physical" circle="11"/>
	<DEFENSE kind="social" circle="11"/>
	<DISZIPLINETALENT name="Vitality" circle="11"/>
	<DEFENSE kind="physical" circle="12"/>
	<DISZIPLINETALENT name="Unmount" circle="12"/>
	<OPTIONALTALENT name="Etherreal Weapon" circle="13"/>
	<OPTIONALTALENT name="Mind Blade" circle="13"/>
	<OPTIONALTALENT name="Rushing Attack" circle="13"/>
	<OPTIONALTALENT name="Second Chance" circle="13"/>
	<OPTIONALTALENT name="Vital Strike" circle="13"/>
	<OPTIONALTALENT name="Weapon Beater" circle="13"/>
	<ABILITY name="Resurrect Self" circle="13"/>
	<DEFENSE kind="spell" circle="13"/>
	<INITIATIVE circle="13"/>
	<DISZIPLINETALENT name="Stone Skin" circle="13"/>
	<DEFENSE kind="physical" circle="14"/>
	<INITIATIVE circle="13"/>
	<DISZIPLINETALENT name="Multi-Strike" circle="14"/>
	<DEFENSE kind="spell" circle="15"/>
	<DEFENSE kind="social" circle="15"/>
	<DISZIPLINETALENT name="Aura Armor" circle="15"/>
</DISCIPLINE>

=== EriJan/Earthdawn-Character-Editor/config/disciplines/Wizard.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<DISCIPLINE name="Wizard" lang="en" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../earthdawndiscipline.xsd">
	<DURABILITY circle="1" death="4" unconsciousness="3"/>
	<OPTIONALTALENT name="Acarne Mutterings" circle="1"/>
	<OPTIONALTALENT name="Conversation" circle="1"/>
	<OPTIONALTALENT name="Creature Analysis" circle="1"/>
	<OPTIONALTALENT name="Evidence Analysis" circle="1"/>
	<OPTIONALTALENT name="Spell Matrix" circle="1"/>
	<DISCIPLINETALENT name="Astral Sight" circle="1"/>
	<DISCIPLINETALENT name="Karma Ritual" circle="1"/>
	<DISCIPLINETALENT name="Read/Write Magic" circle="1"/>
	<DISCIPLINETALENT name="Spellcasting" circle="1"/>
	<DISCIPLINETALENT name="Spell Matrix" circle="1"/>
	<DISCIPLINETALENT name="Thread Weaving" circle="1" limitation="Wizardry"/>
	<SPELL type="wizard" name="Astral Sense" circle="1"/>
	<SPELL type="wizard" name="Bedazzling Display of Logical Analysis" circle="1"/>
	<SPELL type="wizard" name="Crushing Will" circle="1"/>
	<SPELL type="wizard" name="Dispel Magic" circle="1"/>
	<SPELL type="wizard" name="Divine Aura" circle="1"/>
	<SPELL type="wizard" name="Flame Flash" circle="1"/>
	<SPELL type="wizard" name="Ignite" circle="1"/>
	<SPELL type="wizard" name="Iron Hand" circle="1"/>
	<SPELL type="wizard" name="Mind Dagger" circle="1"/>
	<SPELL type="wizard" name="Silent Converse" circle="1"/>
	<SPELL type="wizard" name="Triangulate" circle="1"/>
	<SPELL type="wizard" name="Wall Walker" circle="1"/>
	<OPTIONALTALENT name="Abate Curse" circle="2"/>
	<OPTIONALTALENT name="Detect Weapon" circle="2"/>
	<OPTIONALTALENT name="Durability" circle="2" limitation="4/3"/>
	<OPTIONALTALENT name="Item History" circle="2"/>
	<OPTIONALTALENT name="Search" circle="2"/>
	<OPTIONALTALENT name="Speak Language" circle="2"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<DISCIPLINETALENT name="Read/Write Language" circle="2"/>
	<SPELL type="wizard" name="And His Money" circle="2"/>
	<SPELL type="wizard" name="Astral Shield" circle="2"/>
	<SPELL type="wizard" name="Clean" circle="2"/>
	<SPELL type="wizard" name="Dodge Boost" circle="2"/>
	<SPELL type="wizard" name="Rope Ladder" circle="2"/>
	<SPELL type="wizard" name="Seal" circle="2"/>
	<SPELL type="wizard" name="Vines" circle="2"/>
	<SPELL type="wizard" name="Wake-Up Call" circle="2"/>
	<SPELLABILITY circle="2"/>
	<DEFENSE kind="spell" circle="2"/>
	<DISCIPLINETALENT name="Book Memory" circle="3"/>
	<SPELL type="wizard" name="Aura Strike" circle="3"/>
	<SPELL type="wizard" name="Catwalk" circle="3"/>
	<SPELL type="wizard" name="Combat Fury" circle="3"/>
	<SPELL type="wizard" name="False Aura" circle="3"/>
	<SPELL type="wizard" name="Healing Sleep" circle="3"/>
	<SPELL type="wizard" name="Identify Spell" circle="3"/>
	<SPELL type="wizard" name="Leaps and Bounds" circle="3"/>
	<SPELL type="wizard" name="Levitate" circle="3"/>
	<SPELL type="wizard" name="Notice Not" circle="3"/>
	<SPELL type="wizard" name="Ork Stoke" circle="3"/>
	<SPELL type="wizard" name="Quicken Pace" circle="3"/>
	<SPELL type="wizard" name="Seeking Sight" circle="3"/>
	<SPELL type="wizard" name="Shatter Lock" circle="3"/>
	<SPELL type="wizard" name="Water Wings" circle="3"/>
	<SPELL type="wizard" name="Wizard Mark" circle="3"/>
	<SPELLABILITY circle="3"/>
	<DISCIPLINETALENT name="Research" circle="4"/>
	<SPELL type="wizard" name="Ball of String" circle="4"/>
	<SPELL type="wizard" name="Binding Threads" circle="4"/>
	<SPELL type="wizard" name="Buoyancy" circle="4"/>
	<SPELL type="wizard" name="Dust Devil" circle="4"/>
	<SPELL type="wizard" name="Hair Frenzy" circle="4"/>
	<SPELL type="wizard" name="Icy Protection" circle="4"/>
	<SPELL type="wizard" name="Identify Magic" circle="4"/>
	<SPELL type="wizard" name="Inventory" circle="4"/>
	<SPELL type="wizard" name="Juggler's Touch" circle="4"/>
	<SPELL type="wizard" name="Kaer Knocking" circle="4"/>
	<SPELL type="wizard" name="Karmic Connection" circle="4"/>
	<SPELL type="wizard" name="Relax" circle="4"/>
	<SPELL type="wizard" name="Repair Lock" circle="4"/>
	<SPELL type="wizard" name="Thorny Retreat" circle="4"/>
	<SPELL type="wizard" name="Trust" circle="4"/>
	<SPELL type="wizard" name="Wizard's Cloak" circle="4"/>
	<SPELLABILITY circle="4"/>
	<KARMA spend="Perception-only Test" circle="4"/>
	<OPTIONALTALENT name="Detect Trap" circle="5"/>
	<OPTIONALTALENT name="Direction Sense" circle="5"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Lifesight" circle="5"/>
	<OPTIONALTALENT name="Lip Reading" circle="5"/>
	<OPTIONALTALENT name="Orbiting Spy" circle="5"/>
	<OPTIONALTALENT name="Willforce" circle="5"/>
	<DISCIPLINETALENT name="Steel Thought" circle="5"/>
	<SPELL type="wizard" name="Counterspell" circle="5"/>
	<SPELL type="wizard" name="Giant Size" circle="5"/>
	<SPELL type="wizard" name="Heat Metal Armor" circle="5"/>
	<SPELL type="wizard" name="Invigorate" circle="5"/>
	<SPELL type="wizard" name="Kaer Pictographs" circle="5"/>
	<SPELL type="wizard" name="Mage Armor" circle="5"/>
	<SPELL type="wizard" name="Makeshift Missile" circle="5"/>
	<SPELL type="wizard" name="Mystic Shock" circle="5"/>
	<SPELL type="wizard" name="Sanctuary" circle="5"/>
	<SPELL type="wizard" name="Slow" circle="5"/>
	<SPELL type="wizard" name="Solo Flight" circle="5"/>
	<SPELL type="wizard" name="Study Thread" circle="5"/>
	<SPELLABILITY circle="5"/>
	<ABILITY name="Book Mage" circle="5"/>
	<DISCIPLINETALENT name="Book Recall" circle="6"/>
	<SPELL type="wizard" name="Blood Lost" circle="6"/>
	<SPELL type="wizard" name="Displace Self" circle="6"/>
	<SPELL type="wizard" name="Doom Missile" circle="6"/>
	<SPELL type="wizard" name="Karma Cancel" circle="6"/>
	<SPELL type="wizard" name="Loan Spell" circle="6"/>
	<SPELL type="wizard" name="Makeshift Weapon" circle="6"/>
	<SPELL type="wizard" name="Mental Library" circle="6"/>
	<SPELL type="wizard" name="Multi-Mind Dagger" circle="6"/>
	<SPELL type="wizard" name="Rampage" circle="6"/>
	<SPELL type="wizard" name="Razor Orb" circle="6"/>
	<SPELL type="wizard" name="Sleep" circle="6"/>
	<SPELL type="wizard" name="Spellstore" circle="6"/>
	<KARMA spend="Willpower-Only Tests" circle="6"/>
	<DISCIPLINETALENT name="Resist Taunt" circle="7"/>
	<SPELL type="wizard" name="Astral Gift" circle="7"/>
	<SPELL type="wizard" name="Blood Boil" circle="7"/>
	<SPELL type="wizard" name="Call" circle="7"/>
	<SPELL type="wizard" name="Confusing Weave" circle="7"/>
	<SPELL type="wizard" name="Dislodge Spell" circle="7"/>
	<SPELL type="wizard" name="Lightning Cloud" circle="7"/>
	<SPELL type="wizard" name="Liquid Eyes" circle="7"/>
	<SPELL type="wizard" name="Move on Through" circle="7"/>
	<SPELL type="wizard" name="Mystic Net" circle="7"/>
	<SPELL type="wizard" name="Spell Cage" circle="7"/>
	<KARMA spend="spell effect tests" circle="7"/>
	<DISCIPLINETALENT name="Hold Thread" circle="8"/>
	<SPELL type="wizard" name="Catch Spell" circle="8"/>
	<SPELL type="wizard" name="Compression Bubble" circle="8"/>
	<SPELL type="wizard" name="Delay Blow" circle="8"/>
	<SPELL type="wizard" name="Peacebond" circle="8"/>
	<SPELL type="wizard" name="Safe Opening" circle="8"/>
	<SPELL type="wizard" name="Spell Snatcher" circle="8"/>
	<SPELL type="wizard" name="Wound Mask" circle="8"/>
	<DEFENSE circle="8" kind="spell"/>
</DISCIPLINE>
