=== EriJan/Earthdawn-Character-Editor/config/earthdawnrandomname.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/randomname" xmlns="http://earthdawn.com/randomname" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="RANDOMNAME_RACE_type">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="RANDOMNAME_NAMEPART" type="RANDOMNAME_NAMES_type"/>
		</xs:sequence>
		<xs:attribute name="race" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="RANDOMNAME_NAMES_type">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="part" type="edt:unsigned_int" default="0"/>
				<xs:attribute name="gender" type="edt:gender_type" default="-"/>
				<xs:attribute name="delimer" type="xs:string" default=" "/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="EDRANDOMNAME">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="RANDOMNAME_RACE" type="RANDOMNAME_RACE_type"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/config/randomnames.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<EDRANDOMNAME xmlns="http://earthdawn.com/randomname" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/randomname earthdawnrandomname.xsd">
	<RANDOMNAME_RACE race="Dwarf">
		<RANDOMNAME_NAMEPART part="0" gender="female">achatell aquial bapuea bapuy baschy dorilly fanlike galfie gilly igrami Jaella jatraschya kiry kleiyie Learka Maera mergrima mergrimya morianell obsidianial obsidya platinea platiny saphirell Seadda segalnall segalnell segalnial segalnya sloncia wapargall waparge yania Ysilla</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">alfregg Agnar arex Bariv baver bulim Carnadan Dagnus Del Egin engarim etogosch fasakel Fignus Glorin grepius grirr gumgelf himbez Hofur irmeam kagrem Kordur lemosch levom Lognar lugom mekel merrox Moran morax morram myrr Noran obalosch ogalme parilex Paranur rabogasch Renar schilbimg Sunar Thom thorek thorim turweck Tusur tuwer Ulrun Varulus Vignor vinelfr Vunar Zognar</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">axthauer axtschwinger bergschmied breithelm donnerstein eisenfaust eisenhammer eisenheim eisenrein eisenstolz erdauge feuerwerk gassenzwerg goldheim goldschmuck Hammerblade hammerblut hammertanz isenformer isenklang kupferbart kupferblut Rieka schmiedeeisen silberblut silberfaust silberglanz silberhaar stahlblick steinreich</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Elf">
		<RANDOMNAME_NAMEPART part="0">adan aelin alquar annon arien atar avari barad bragol brethil carak carakquen celeb coron dagor Eirdeth eldar Gaelin glínrith hadlon laurwen Luevia marach melwer moriquendi Nai’ara noldor quendi qwaith telpe Tyrnea vanyië</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">adurídûnê Aeraias aerávién alquóque argélohar atagdûr Belphegor Beshar borarína Caelarion Caluath curánil Delthrien Dremnin Daa dimile dungâmbar earinirist erariand Eytherian Farliv fingaya Fithvael firnulach fuínahel gulinost Hareth Iathi ivênost ivreriand Jaren Jerreck Karon Kermanthil Lianar managorn Maralan Mestoph mírênael morwurúth nahála námíhabar Noarethal Pyrail ramadris raméler ranogdûr seróvrin Siluath sulige Tiathar tuminna vinálas vingálachel Weng Yalathael Zydan</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">Evensong</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE> 
	<RANDOMNAME_RACE race="Gar">
		<RANDOMNAME_NAMEPART part="0" gender="female"></RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Naran</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">Khan</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Human">
		<RANDOMNAME_NAMEPART part="0" gender="female" delimiter=";">Celina;Galdora;Igna;Kelandra;Nahindra;Ophelia;Quelana</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male" delimiter=";">Alachrim;Alvar;Baldred;Cymric;Daylen;Delmor;Elwind;Fenwill;Gandalar;Gillian;Honguth;Hyram;Jel;J’Role;Lamand;Melgador;Pandur;Rigus;Santorano;Timbur;Ulgur;Vendar;Wilbur;Yan;Yanno;Xandir;Zidan</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1" delimiter=";">Goerm;Jagaro;Lang;Mammo</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Ki Mao">
		<RANDOMNAME_NAMEPART part="0" gender="female"></RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Jun</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">Lu</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Obsidimen">
		<RANDOMNAME_NAMEPART part="0" gender="female"></RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Amaltham Belarus Cedrok domasae Domnur Erathun Forr Gothus Haralayelus Imodun Jarralak Kolarat Korum Laramanus Monuk Nostrus Omasu Omeyras Onnaro Ophranim Physt Quaron Redurus Sogun Torukor Uhnar Voltor Wethysor Xamdar Ygasu</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Ork">
		<RANDOMNAME_NAMEPART part="0" gender="female"></RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Aluk Brog Curst Drognur Ekarr Faghn Garon Gors Gragok Hamvel Horak Jurok Karoar Kartos Kia’k Kraeg Krolok Lorga Malgat Mornur Nago Orkal Pahok Quan Ristar Tadhg Tok Uvul Ulag Venag Y’lomm Zugrut</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">Manystones Yelloweye</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE> 
	<RANDOMNAME_RACE race="Po Na">
		<RANDOMNAME_NAMEPART part="0" gender="female"></RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Lang</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">Hi</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Storm Children">
		<RANDOMNAME_NAMEPART part="0" gender="female">Fey</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male"></RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1"></RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Troll">
		<RANDOMNAME_NAMEPART part="0" gender="female">Skorja</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Barak Belwharg Belgaras Bormak Chag Crygath Dogul Dul’Gaar Emkor Fograk Ganlor Holdur Irrgam Jarth’d Jorkaw Kaan Karok Larus Lorm Lorrm Mongur Narkys Orrguth Osker Pawkarr Quindor Rothur Starrk Tahst Targ Twak’dar Urdon Vigord Wrogath Yggerg Zisgul</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1">Baldurion Boneslicer Skat</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE> 
	<RANDOMNAME_RACE race="T´skrang">
		<RANDOMNAME_NAMEPART part="0" gender="female">Ch’isha Ss’kala T’aysta</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Aysusul Ayapagoam Aychasu D’zurr Gris’kall Ka’Daiyen Kar’rath Kricklas Kricklen Kenshan Rh’gullian R’ressnosh San’t Segue P’shalmar Schlome Shisa’kas Syrkhan T’sabur T’shystalan Vash’sten V’stogas Yoke Z’rrt’shulam</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="1"></RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
	<RANDOMNAME_RACE race="Windling">
		<RANDOMNAME_NAMEPART part="0" gender="female">Aylaa Cydiilya Nyataij Vaylaa</RANDOMNAME_NAMEPART>
		<RANDOMNAME_NAMEPART part="0" gender="male">Broomé Buukh Daalan Ekidii Faylaa Filtch Ghooru Gesaale Hakudaa Ijundaa Joorn Kaarth Leeth Manataas Osildaas Poorht Poosim Qendaar Pooth Seethian Syildijan Thalon Tinsoo Ukayaar Xastiin Zorisanaal</RANDOMNAME_NAMEPART>
	</RANDOMNAME_RACE>
</EDRANDOMNAME>
