=== EriJan/Earthdawn-Character-Editor/config/earthdawnrandomcharactertemplate.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/randomcharactertemplate" xmlns="http://earthdawn.com/randomcharactertemplate" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="weightedstringlist_type">
		<xs:simpleContent>
			<xs:extension base="edt:stringlist_type">
				<xs:attribute name="weight" type="edt:unsigned_int" default="1"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="RANDOMATTRIBUTES_type">
		<xs:attribute name="weight" type="edt:unsigned_int" default="1"/>
		<xs:attribute name="attribute" type="edt:ATTRIBUTE_name_type" use="required"/>
	</xs:complexType>
	<xs:complexType name="RANDOMSPELLCATEGORY_type">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="SPELLS" type="weightedstringlist_type"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" default=""/>
		<xs:attribute name="min" type="edt:unsigned_int" default="1"/>
		<xs:attribute name="max" type="edt:unsigned_int" default="1"/>
	</xs:complexType>
	<xs:complexType name="RANDOMITEMCATEGORY_type">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="ITEMS" type="weightedstringlist_type"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" default=""/>
		<xs:attribute name="min" type="edt:unsigned_int" default="1"/>
		<xs:attribute name="max" type="edt:unsigned_int" default="1"/>
	</xs:complexType>
	<xs:element name="EDRANDOMCHARACTERTEMPLATE">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="RACES" type="weightedstringlist_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="ATTRIBUTES" type="RANDOMATTRIBUTES_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="DISCIPLINES" type="weightedstringlist_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="SPELLCATEGORY" type="RANDOMSPELLCATEGORY_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="SKILLS" type="weightedstringlist_type"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="ITEMCATEGORY" type="RANDOMITEMCATEGORY_type"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="circle_min" type="edt:unsigned_int" default="1"/>
			<xs:attribute name="circle_max" type="edt:unsigned_int" default="15"/>
			<xs:attribute name="skill_min" type="edt:unsigned_int" default="8"/>
			<xs:attribute name="skill_max" type="edt:unsigned_int" default="8"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/config/randomcharactertemplates/scorcher.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<EDRANDOMCHARACTERTEMPLATE lang="en" name="Scorcher c5-10" circle_min="5" circle_max="10" xmlns="http://earthdawn.com/randomcharactertemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/randomcharactertemplate ../earthdawnrandomcharactertemplate.xsd">
	<RACES weight="20">Ork</RACES>
	<RACES weight="1">Human</RACES>
	<RACES weight="1">Troll</RACES>
	<ATTRIBUTES attribute="DEX" weight="10" />
	<ATTRIBUTES attribute="STR" weight="7" />
	<ATTRIBUTES attribute="TOU" weight="7" />
	<ATTRIBUTES attribute="PER" weight="3" />
	<ATTRIBUTES attribute="WIL" weight="1" />
	<ATTRIBUTES attribute="CHA" weight="10" />
	<DISCIPLINES weight="12">Cavalryman</DISCIPLINES>
	<DISCIPLINES weight="6">Warrior</DISCIPLINES>
	<DISCIPLINES weight="2">Beastmaster</DISCIPLINES>
	<DISCIPLINES weight="2" delimiter=",">Sky Raider</DISCIPLINES>
	<SKILLS delimiter=";">Detect Trap;Disarm Trap;Surprise Strike;Trap Initiative;Search;Tracking;Haggle;Animal Handling;Avoid Blow</SKILLS>
	<ITEMCATEGORY name="weapon" min="1" max="3">
		<ITEMS delimiter=",">Broadsword,Battle Axe,Short Sword</ITEMS>
	</ITEMCATEGORY>
	<ITEMCATEGORY name="armor" min="1" max="1">
		<ITEMS delimiter=",">Hardened Leather,Padded Leather,Hide</ITEMS>
	</ITEMCATEGORY>
	<ITEMCATEGORY name="shield" min="1" max="1">
		<ITEMS>Buckler Bark Rider's</ITEMS>
	</ITEMCATEGORY>
	<ITEMCATEGORY name="utils">
		<ITEMS delimiter=",">Bedroll,Artisan Tool (rune carving)</ITEMS>
	</ITEMCATEGORY>
</EDRANDOMCHARACTERTEMPLATE>

=== EriJan/Earthdawn-Character-Editor/config/randomcharactertemplates/fighter.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<EDRANDOMCHARACTERTEMPLATE lang="en" name="fighter" circle_min="3" circle_max="6" xmlns="http://earthdawn.com/randomcharactertemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/randomcharactertemplate ../earthdawnrandomcharactertemplate.xsd">
<RACES weight="6" >Dwarf Human Troll Ork</RACES>
<RACES weight="3" >Elf</RACES>
<RACES weight="1" >Windling</RACES>
<ATTRIBUTES attribute="DEX" weight="10"/>
<ATTRIBUTES attribute="STR" weight="9"/>
<ATTRIBUTES attribute="TOU" weight="7"/>
<ATTRIBUTES attribute="PER" weight="3"/>
<ATTRIBUTES attribute="WIL" weight="1"/>
<ATTRIBUTES attribute="CHA" weight="1"/>
<DISCIPLINES weight="8">Warrior Swordmaster</DISCIPLINES>
<DISCIPLINES weight="5">Scout</DISCIPLINES>
<ARMOR delimer=",">Hardened Leather,Padded Leather</ARMOR>
<SHIELD>Buckler Buckler</SHIELD>
<WEAPON>Broadsword</WEAPON>
<SPELLS></SPELLS>
<SKILLS></SKILLS>
<ITEMS category="utils" delimer=",">Bedroll, artisan tool (rune carving)</ITEMS>
</EDRANDOMCHARACTERTEMPLATE>
