=== EriJan/Earthdawn-Character-Editor/config/earthdawndiscipline.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/discipline" xmlns="http://earthdawn.com/discipline" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="CIRCLENAME_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="DISZIPINABILITY_type">
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="TALENTABILITY_type">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="limitation" type="xs:string" default=""/>
	</xs:complexType>
	<xs:complexType name="KARMAABILITY_type">
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="spend" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="DEFENSEABILITY_type">
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="kind" type="edt:defensekind_type" default="physical"/>
	</xs:complexType>
	<xs:element name="DISCIPLINE">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element maxOccurs="unbounded" minOccurs="0" name="DISZIPLINETALENT" type="TALENTABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="OPTIONALTALENT" type="TALENTABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="KARMA" type="KARMAABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="ABILITY" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="DEFENSE" type="DEFENSEABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="INITIATIVE" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="RECOVERYTEST" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="KARMASTEP" type="DISZIPINABILITY_type"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="SPELL" type="DISZIPINABILITY_type"/>
			</xs:choice>
			<xs:attribute name="lang" type="edt:language_type" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/config/disciplines/Illusionist.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<DISCIPLINE name="Illusionist" lang="en" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../earthdawndiscipline.xsd">
	<DURABILITY circle="1" death="4" unconsciousness="3"/>
	<OPTIONALTALENT name="Astral Sight" circle="1"/>
	<OPTIONALTALENT name="First Impression" circle="1"/>
	<OPTIONALTALENT name="Read/Write Language" circle="1"/>
	<OPTIONALTALENT name="Silent Walk" circle="1"/>
	<OPTIONALTALENT name="Spell Matrix" circle="1"/>
	<DISCIPLINETALENT name="Karma Ritual" circle="1"/>
	<DISCIPLINETALENT name="Read/Write Magic" circle="1"/>
	<DISCIPLINETALENT name="Speak Language" circle="1"/>
	<DISCIPLINETALENT name="Spellcasting" circle="1"/>
	<DISCIPLINETALENT name="Spell Matrix" circle="1"/>
	<DISCIPLINETALENT name="Thread Weaving" circle="1" limitation="Illusionism"/>
	<SPELL type="illusion" name="Assuring Touch" circle="1"/>
	<SPELL type="illusion" name="Bellow of the Thundras" circle="1"/>
	<SPELL type="illusion" name="Best Face" circle="1"/>
	<SPELL type="illusion" name="Blazing Fists of Rage" circle="1"/>
	<SPELL type="illusion" name="Catseyes" circle="1"/>
	<SPELL type="illusion" name="Disguise Metal" circle="1"/>
	<SPELL type="illusion" name="Displace Image" circle="1"/>
	<SPELL type="illusion" name="Fun With Doors" circle="1"/>
	<SPELL type="illusion" name="Light" circle="1"/>
	<SPELL type="illusion" name="Pauper's Purse" circle="1"/>
	<SPELL type="illusion" name="Rope Guide" circle="1"/>
	<SPELL type="illusion" name="True Blazing Fists of Rage" circle="1"/>
	<SPELL type="illusion" name="Unseen Voices" circle="1"/>
	<OPTIONALTALENT name="Arcane Mutterings" circle="2"/>
	<OPTIONALTALENT name="Durability" circle="2" limitation="4/3"/>
	<OPTIONALTALENT name="Frighten" circle="2"/>
	<OPTIONALTALENT name="Haggle" circle="2"/>
	<OPTIONALTALENT name="Mimic Voice" circle="2"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<OPTIONALTALENT name="Winning Smile" circle="2"/>
	<DISCIPLINETALENT name="Disguise Self" circle="2"/>
	<SPELL type="illusion" name="Blindness" circle="2"/>
	<SPELL type="illusion" name="Crafty Thought" circle="2"/>
	<SPELL type="illusion" name="Disaster" circle="2"/>
	<SPELL type="illusion" name="Encrypt" circle="2"/>
	<SPELL type="illusion" name="Ephemeral Bolt" circle="2"/>
	<SPELL type="illusion" name="Impossible Knot" circle="2"/>
	<SPELL type="illusion" name="Innocent Activity" circle="2"/>
	<SPELL type="illusion" name="Monstrous Mantle" circle="2"/>
	<SPELL type="illusion" name="Remove Shadow" circle="2"/>
	<SPELL type="illusion" name="Send Message" circle="2"/>
	<SPELL type="illusion" name="Tailor" circle="2"/>
	<SPELL type="illusion" name="True Ephemeral Bolt" circle="2"/>
	<SPELL type="illusion" name="Weather Cloak" circle="2"/>
	<SPELL type="illusion" name="You Got Me" circle="2"/>
	<DEFENSE kind="spell" circle="2"/>
	<DISCIPLINETALENT name="Dead Fall" circle="3"/>
	<SPELL type="illusion" name="Alarm" circle="3"/>
	<SPELL type="illusion" name="And Then I Woke Up" circle="3"/>
	<SPELL type="illusion" name="Blinding Glare" circle="3"/>
	<SPELL type="illusion" name="Dampen Karma" circle="3"/>
	<SPELL type="illusion" name="Detect Illusionism Magic" circle="3"/>
	<SPELL type="illusion" name="Dispel Illusionism Magic" circle="3"/>
	<SPELL type="illusion" name="False Floor" circle="3"/>
	<SPELL type="illusion" name="Impossible Lock" circle="3"/>
	<SPELL type="illusion" name="Mind Fog" circle="3"/>
	<SPELL type="illusion" name="Nobody Here" circle="3"/>
	<SPELL type="illusion" name="Phantom Warrior" circle="3"/>
	<SPELL type="illusion" name="See the Unseen" circle="3"/>
	<SPELL type="illusion" name="Soothe the Savage Beast" circle="3"/>
	<SPELL type="illusion" name="Suffocation" circle="3"/>
	<SPELLABILITY circle="3"/>
	<DISCIPLINETALENT name="False Sight" circle="4"/>
	<SPELL type="illusion" name="Aura" circle="4"/>
	<SPELL type="illusion" name="Bleeding Edge" circle="4"/>
	<SPELL type="illusion" name="Circle of Well Being" circle="4"/>
	<SPELL type="illusion" name="Clarion Call" circle="4"/>
	<SPELL type="illusion" name="Conceal Tracks" circle="4"/>
	<SPELL type="illusion" name="Eyes Have It" circle="4"/>
	<SPELL type="illusion" name="Great Weapon" circle="4"/>
	<SPELL type="illusion" name="Hunger" circle="4"/>
	<SPELL type="illusion" name="Improved Alarm" circle="4"/>
	<SPELL type="illusion" name="Memory Blank" circle="4"/>
	<SPELL type="illusion" name="Multi-Missile" circle="4"/>
	<SPELL type="illusion" name="Nightmare of Foreboding" circle="4"/>
	<SPELL type="illusion" name="Stop Right There" circle="4"/>
	<SPELL type="illusion" name="Unmask" circle="4"/>
	<SPELLABILITY circle="4"/>
	<KARMA spend="Perception-only Test" circle="4"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Graceful Exit" circle="5"/>
	<OPTIONALTALENT name="Hypnotzize" circle="5"/>
	<OPTIONALTALENT name="Resist Taunt" circle="5"/>
	<OPTIONALTALENT name="Slough Blame" circle="5"/>
	<OPTIONALTALENT name="Steel Thought" circle="5"/>
	<OPTIONALTALENT name="Willforce" circle="5"/>
	<DISCIPLINETALENT name="True Sight" circle="5"/>
	<SPELL type="illusion" name="Awaken" circle="5"/>
	<SPELL type="illusion" name="Bond of Silence" circle="5"/>
	<SPELL type="illusion" name="Clothing Gone" circle="5"/>
	<SPELL type="illusion" name="Enter and Exit" circle="5"/>
	<SPELL type="illusion" name="Eye of Truth" circle="5"/>
	<SPELL type="illusion" name="Flesh Eater" circle="5"/>
	<SPELL type="illusion" name="Flying Carpet" circle="5"/>
	<SPELL type="illusion" name="Illusion" circle="5"/>
	<SPELL type="illusion" name="Improve Karma" circle="5"/>
	<SPELL type="illusion" name="Noble Manner" circle="5"/>
	<SPELL type="illusion" name="Phantom Fireball" circle="5"/>
	<SPELL type="illusion" name="Pleasant Visions" circle="5"/>
	<SPELL type="illusion" name="Switch" circle="5"/>
	<SPELL type="illusion" name="Wall of Unfire" circle="5"/>
	<SPELLABILITY circle="5"/>
	<ABILITY name="Glamour" circle="5"/>
	<DISCIPLINETALENT name="Engaging Banter" circle="6"/>
	<SPELL type="illusion" name="Astral Shadow" circle="6"/>
	<SPELL type="illusion" name="Bouncing Blaster" circle="6"/>
	<SPELL type="illusion" name="Chosen Path" circle="6"/>
	<SPELL type="illusion" name="Dancing Disks" circle="6"/>
	<SPELL type="illusion" name="Foreseeing" circle="6"/>
	<SPELL type="illusion" name="Illusory Missiles" circle="6"/>
	<SPELL type="illusion" name="Memory Scribe" circle="6"/>
	<SPELL type="illusion" name="Spotlight" circle="6"/>
	<SPELL type="illusion" name="Stench" circle="6"/>
	<KARMA spend="Willpower-only Test" circle="7"/>
	<DISCIPLINETALENT name="Fast Hand" circle="7"/>
	<SPELL type="illusion" name="Dream Sight" circle="7"/>
	<SPELL type="illusion" name="Drunken Stagger" circle="7"/>
	<SPELL type="illusion" name="False Enchantment" circle="7"/>
	<SPELL type="illusion" name="Rebel Limb" circle="7"/>
	<SPELL type="illusion" name="Reversal of Passion" circle="7"/>
	<SPELL type="illusion" name="Silent Stampede" circle="7"/>
	<SPELL type="illusion" name="Stampede" circle="7"/>
	<SPELL type="illusion" name="Time Flies" circle="7"/>
	<SPELL type="illusion" name="Twisted Tongues" circle="7"/>
	<SPELL type="illusion" name="Vertigo" circle="7"/>
	<SPELL type="illusion" name="Walk Through" circle="7"/>
	<KARMA spend="spell effect tests" circle="7"/>
	<DISCIPLINETALENT name="Power Mask" circle="8"/>
	<SPELL type="illusion" name="Astral Nightmare" circle="8"/>
	<SPELL type="illusion" name="Dreamsend" circle="8"/>
	<SPELL type="illusion" name="Form Exchange" circle="8"/>
	<SPELL type="illusion" name="Leaping Lizards" circle="8"/>
	<SPELL type="illusion" name="Massive Missiles" circle="8"/>
	<SPELL type="illusion" name="Other Place" circle="8"/>
	<SPELL type="illusion" name="Shadow Spell" circle="8"/>
	<DEFENSE circle="8" kind="spell"/>
</DISCIPLINE>

=== EriJan/Earthdawn-Character-Editor/config/disciplines/Elementalist.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<DISCIPLINE name="Elementalist" lang="en" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../earthdawndiscipline.xsd">
	<DURABILITY circle="2" death="4" unconsciousness="3"/>
	<OPTIONALTALENT name="Arcane Mutterings" circle="1"/>
	<OPTIONALTALENT name="Haggle" circle="1"/>
	<OPTIONALTALENT name="Read/Write Language" circle="1"/>
	<OPTIONALTALENT name="Speak Language" circle="1"/>
	<OPTIONALTALENT name="Spell Matrix" circle="1"/>
	<DISCIPLINETALENT name="Air Speaking" circle="1"/>
	<DISCIPLINETALENT name="Karma Ritual" circle="1"/>
	<DISCIPLINETALENT name="Spellcasting" circle="1"/>
	<DISCIPLINETALENT name="Read/Write Magic" circle="1"/>
	<DISCIPLINETALENT name="Thread Weaving" circle="1" limitation="Elementalism"/>
	<DISCIPLINETALENT name="Spell Matrix" circle="1"/>
	<SPELL type="elemental" name="Air Armor" circle="1"/>
	<SPELL type="elemental" name="Crunch Climb" circle="1"/>
	<SPELL type="elemental" name="Earth Blend" circle="1"/>
	<SPELL type="elemental" name="Earth Darts" circle="1"/>
	<SPELL type="elemental" name="Flameweapon" circle="1"/>
	<SPELL type="elemental" name="Heat Food" circle="1"/>
	<SPELL type="elemental" name="Moonglow" circle="1"/>
	<SPELL type="elemental" name="Plant Talk" circle="1"/>
	<SPELL type="elemental" name="Purify Earth" circle="1"/>
	<SPELL type="elemental" name="Purify Water" circle="1"/>
	<SPELL type="elemental" name="Resist Cold" circle="1"/>
	<SPELL type="elemental" name="Resist Fire" circle="1"/>
	<DEFENSE kind="spell" circle="2"/>
	<OPTIONALTALENT name="Astral Sight" circle="2"/>
	<OPTIONALTALENT name="Item History" circle="2"/>
	<OPTIONALTALENT name="Parry" circle="2"/>
	<OPTIONALTALENT name="Durability" circle="2" limitation="4/3"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<OPTIONALTALENT name="Tracking" circle="2"/>
	<OPTIONALTALENT name="Wind Catcher" circle="2"/>
	<DISCIPLINETALENT name="Fire Heal" circle="2"/>
	<SPELL type="elemental" name="Air Mattress" circle="2"/>
	<SPELL type="elemental" name="Billowing Cloak" circle="2"/>
	<SPELL type="elemental" name="Boil Water" circle="2"/>
	<SPELL type="elemental" name="Detect Elementalism Magic" circle="2"/>
	<SPELL type="elemental" name="Flame Strike" circle="2"/>
	<SPELL type="elemental" name="Grills" circle="2"/>
	<SPELL type="elemental" name="Hunter's Sense" circle="2"/>
	<SPELL type="elemental" name="Ice Spear" circle="2"/>
	<SPELL type="elemental" name="Icy Surface" circle="2"/>
	<SPELL type="elemental" name="Path Home" circle="2"/>
	<SPELL type="elemental" name="Shield Willow" circle="2"/>
	<SPELL type="elemental" name="Slow Metal Weapon" circle="2"/>
	<SPELL type="elemental" name="Small Slayer" circle="2"/>
	<SPELL type="elemental" name="Sterilize Object" circle="2"/>
	<SPELL type="elemental" name="Stick Together" circle="2"/>
	<DISCIPLINETALENT name="Elemental Tongues" circle="3"/>
	<SPELL type="elemental" name="Behind Eye" circle="3"/>
	<SPELL type="elemental" name="Dispel Elementalism Magic" circle="3"/>
	<SPELL type="elemental" name="Fingers of Wind" circle="3"/>
	<SPELL type="elemental" name="Fuel Flame" circle="3"/>
	<SPELL type="elemental" name="Grounding" circle="3"/>
	<SPELL type="elemental" name="Ice Mace and Chain" circle="3"/>
	<SPELL type="elemental" name="Lightning Bolt" circle="3"/>
	<SPELL type="elemental" name="Plant Feast" circle="3"/>
	<SPELL type="elemental" name="Porter" circle="3"/>
	<SPELL type="elemental" name="Puddle Deep" circle="3"/>
	<SPELL type="elemental" name="Repair" circle="3"/>
	<SPELL type="elemental" name="Rust" circle="3"/>
	<SPELL type="elemental" name="Sky Lattice" circle="3"/>	
	<SPELL type="elemental" name="Smoke Cloud" circle="3"/>
	<SPELL type="elemental" name="Snuff" circle="3"/>
	<SPELL type="elemental" name="Sunlight" circle="3"/>
	<SPELL type="elemental" name="Thrive" circle="3"/>
	<SPELL type="elemental" name="Throne of Air" circle="3"/>
	<SPELL type="elemental" name="Winds of Deflection" circle="3"/>
	<DISCIPLINETALENT name="Elemental Hold" circle="4"/>
	<SPELL type="elemental" name="Air Blast" circle="4"/>
	<SPELL type="elemental" name="Blizzard Sphere" circle="4"/>
	<SPELL type="elemental" name="[Element] Spear" circle="4"/>
	<SPELL type="elemental" name="Falcon's Cloak" circle="4"/>
	<SPELL type="elemental" name="Fire Whip" circle="4"/>
	<SPELL type="elemental" name="Great Sticky Vines" circle="4"/>
	<SPELL type="elemental" name="Lighten Load" circle="4"/>		
	<SPELL type="elemental" name="Lightning Shield" circle="4"/>
	<SPELL type="elemental" name="Lightning Step" circle="4"/>
	<SPELL type="elemental" name="Liquid Arrow" circle="4"/>
	<SPELL type="elemental" name="Lodestone's Touch" circle="4"/>
	<SPELL type="elemental" name="Root Trap" circle="4"/>
	<SPELL type="elemental" name="Shield of Warping" circle="4"/>
	<SPELL type="elemental" name="Spirits of Death's Sea" circle="4"/>
	<SPELL type="elemental" name="Suffocating Paste" circle="4"/>
	<SPELL type="elemental" name="Uneven Ground" circle="4"/>
	<SPELL type="elemental" name="Weapon Back" circle="4"/>
	<KARMA spend="Perception-only Test" circle="4"/>
	<OPTIONALTALENT name="Detect Trap" circle="5"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Gliding Stride" circle="5"/>
	<OPTIONALTALENT name="Spot Armor Flaw" circle="5"/>
	<OPTIONALTALENT name="Steal Thought" circle="5"/>
	<OPTIONALTALENT name="Willforce" circle="5"/>
	<OPTIONALTALENT name="Wood Skin" circle="5"/>
	<DISCIPLINETALENT name="Summon" circle="5" limitation="Elemental Spirits"/>
	<SPELL type="elemental" name="Balloons of Mist" circle="5"/>
	<SPELL type="elemental" name="Earth Staff" circle="5"/>
	<SPELL type="elemental" name="Fireball" circle="5"/>
	<SPELL type="elemental" name="Inflame Self" circle="5"/>
	<SPELL type="elemental" name="Ironwood" circle="5"/>
	<SPELL type="elemental" name="Metal Scream" circle="5"/>
	<SPELL type="elemental" name="Metal Wings" circle="5"/>
	<SPELL type="elemental" name="Nutritious Earth" circle="5"/>	
	<SPELL type="elemental" name="Resist Poison" circle="5"/>
	<SPELL type="elemental" name="Shattering Stone" circle="5"/>
	<SPELL type="elemental" name="Stone Cage" circle="5"/>
	<ABILITY name="Fire and Ice" circle="5"/>
	<DISCIPLINETALENT name="Cold Purify" circle="6"/>
	<KARMA spend="Willpower-only Test" circle="6"/>
	<DISCIPLINETALENT name="Earth Skin" circle="7"/>
	<KARMA spend="Spell Effect Test" circle="7"/>
	<DISCIPLINETALENT name="Temperature" circle="8"/>
	<DEFENSE kind="spell" circle="8"/>
	
	
	
</DISCIPLINE>

=== EriJan/Earthdawn-Character-Editor/config/disciplines/Nethermancer.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<DISCIPLINE name="Nethermancer" lang="en" xmlns="http://earthdawn.com/discipline" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/discipline ../earthdawndiscipline.xsd">
	<DURABILITY circle="1" death="4" unconsciousness="3"/>
	<OPTIONALTALENT name="Acarne Mutterings" circle="1"/>
	<OPTIONALTALENT name="Read/Write Language" circle="1"/>
	<OPTIONALTALENT name="Silent Walk" circle="1"/>
	<OPTIONALTALENT name="Speak Language" circle="1"/>
	<OPTIONALTALENT name="Spell Matrix" circle="1"/>
	<DISCIPLINETALENT name="Astral Sight" circle="1"/>
	<DISCIPLINETALENT name="Karma Ritual" circle="1"/>
	<DISCIPLINETALENT name="Read/Write Magic" circle="1"/>
	<DISCIPLINETALENT name="Spellcasting" circle="1"/>
	<DISCIPLINETALENT name="Spell Matrix" circle="1"/>
	<DISCIPLINETALENT name="Thread Weaving" circle="1" limitation="Nethermancy"/>
	<SPELL name="Astral Spear" circle="1"/>
	<SPELL name="Bone Dance" circle="1"/>
	<SPELL name="Chilling Circle" circle="1"/>
	<SPELL name="Command Nightflyer" circle="1"/>
	<SPELL name="Detect Undead" circle="1"/>
	<SPELL name="Dry and Wet" circle="1"/>
	<SPELL name="Experience Death" circle="1"/>
	<SPELL name="Insect Repellent" circle="1"/>
	<SPELL name="Mount Scare" circle="1"/>
	<SPELL name="Puterfy" circle="1"/>
	<SPELL name="Spirit Dart" circle="1"/>
	<SPELL name="Spirit Grip" circle="1"/>
	<SPELL name="Undead Struggle" circle="1"/>
	<OPTIONALTALENT name="Animal Possession" circle="2"/>
	<OPTIONALTALENT name="Blood Share" circle="2"/>
	<OPTIONALTALENT name="Creature Analysis" circle="2"/>
	<OPTIONALTALENT name="Dominate Beast" circle="2"/>
	<OPTIONALTALENT name="Durability" circle="2" limitation="4/3"/>
	<OPTIONALTALENT name="Frighten Animals" circle="2"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<OPTIONALTALENT name="Spell Matrix" circle="2"/>
	<DISCIPLINETALENT name="Frighten" circle="2"/>
	<SPELL name="Bone Cirlce" circle="2"/>
	<SPELL name="Detect Nethermance Magic" circle="2"/>
	<SPELL name="Etherreal Darkness" circle="2"/>
	<SPELL name="Fog Ghost" circle="2"/>
	<SPELL name="Life Circle of One" circle="2"/>
	<SPELL name="Pocket Guardian" circle="2"/>
	<SPELL name="Repel Animal" circle="2"/>
	<SPELL name="Shadow's Whisper" circle="2"/>
	<SPELL name="Shield Mist" circle="2"/>
	<SPELLABILITY circle="2"/>
	<DEFENSE kind="spell" circle="2"/>
	<DISCIPLINETALENT name="Spirit Talk" circle="3"/>
	<SPELL name="Arrow of Night" circle="3"/>
	<SPELL name="Dark Messenger" circle="3"/>
	<SPELL name="Death Trance" circle="3"/>
	<SPELL name="Death's Head" circle="3"/>
	<SPELL name="Dispel Nethermancy Magic" circle="3"/>
	<SPELL name="Fog of Fear" circle="3"/>
	<SPELL name="Grave Message" circle="3"/>
	<SPELL name="Pack Bages" circle="3"/>
	<SPELL name="Pain" circle="3"/>
	<SPELL name="Preserve" circle="3"/>
	<SPELL name="Shadow Meld" circle="3"/>
	<SPELL name="Spirit Double" circle="3"/>
	<SPELL name="Summon Bone Ghost" circle="3"/>
	<SPELLABILITY circle="3"/>
	<DISCIPLINETALENT name="Spirit Hold" circle="4"/>
	<SPELL name="Animate Skeleton" circle="4"/>
	<SPELL name="Astral Flare" circle="4"/>
	<SPELL name="Blood Servitor" circle="4"/>
	<SPELL name="Dark Spy" circle="4"/>
	<SPELL name="Evil Eye" circle="4"/>
	<SPELL name="Fatal Food" circle="4"/>
	<SPELL name="Friend of Foe" circle="4"/>
	<SPELL name="Last Chance" circle="4"/>
	<SPELL name="Nightflyer's Cloak" circle="4"/>
	<SPELL name="Spirit Servant" circle="4"/>
	<SPELL name="Viewpoint" circle="4"/>
	<SPELL name="Visions if Death" circle="4"/>
	<SPELLABILITY circle="4"/>
	<KARMA spend="Willpower-ony Test" circle="4"/>
	<OPTIONALTALENT name="Abate Curse" circle="5"/>
	<OPTIONALTALENT name="Elemental Tongues" circle="5"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Enhanced Matrix" circle="5"/>
	<OPTIONALTALENT name="Item History" circle="5"/>
	<OPTIONALTALENT name="Lion Heart" circle="5"/>
	<OPTIONALTALENT name="Steel Thought" circle="5"/>
	<OPTIONALTALENT name="Willforce" circle="5"/>
	<DISCIPLINETALENT name="Summon" circle="5" limitation="Ally Spirits"/>
	<SPELL name="Animate Spirti Object" circle="5"/>
	<SPELL name="Astral Horror" circle="5"/>
	<SPELL name="Astral Mount" circle="5"/>
	<SPELL name="Astral Whisper" circle="5"/>
	<SPELL name="Blind" circle="5"/>
	<SPELL name="Circle of Atral Protection" circle="5"/>
	<SPELL name="Incessant Talking" circle="5"/>
	<SPELL name="Pass Ward" circle="5"/>
	<SPELL name="Sculpt Darkness" circle="5"/>
	<SPELL name="Sense Horror" circle="5"/>
	<SPELL name="Shadow Hunter" circle="5"/>
	<SPELL name="Spiritual Guidance" circle="5"/>
	<SPELL name="Star Shower" circle="5"/>
	<SPELL name="Target Portal" circle="5"/>
	<SPELL name="Tears of the Scourge" circle="5"/>
	<SPELL name="Whisper Through the Night" circle="5"/>
	<SPELL name="Wither Limb" circle="5"/>
	<SPELLABILITY circle="5"/>
	<ABILITY name="Decay and Renewal" circle="5"/>
	<DISCIPLINETALENT name="Lifesight" circle="6"/>
	<SPELL name="Blessed Light" circle="6"/>
	<SPELL name="Bone Puppet" circle="6"/>
	<SPELL name="Bone Shatter" circle="6"/>
	<SPELL name="Bone Walker" circle="6"/>
	<SPELL name="Dust to Dust" circle="6"/>
	<SPELL name="Foul Vapors" circle="6"/>
	<SPELL name="Friendly Darkness" circle="6"/>
	<SPELL name="Recovery" circle="6"/>
	<SPELL name="Soul Armor" circle="6"/>
	<SPELL name="Wall of Darkness" circle="6"/>
	<SPELLABILITY circle="6"/>
	<KARMA spend="Perseption-Only Tests" circle="6"/>
	<DISCIPLINETALENT name="Spirit Dodge" circle="7"/>
	<SPELL name="Astral Beacon" circle="7"/>
	<SPELL name="Atral Maw" circle="7"/>
	<SPELL name="Banquet of Dis" circle="7"/>
	<SPELL name="Bone Pudding" circle="7"/>
	<SPELL name="Cold Storage" circle="7"/>
	<SPELL name="Constrict Heart" circle="7"/>
	<SPELL name="Damage Shift" circle="7"/>
	<SPELL name="Marathon Run" circle="7"/>
	<SPELL name="Restrain Entity" circle="7"/>
	<SPELL name="Reverse Withering" circle="7"/>
	<SPELL name="Spirit Bold" circle="7"/>
	<SPELL name="Spirit Portal" circle="7"/>
	<SPELL name="Steal Strength" circle="7"/>
	<SPELL name="Step Though Shadow" circle="7"/>
	<SPELL name="Wit Friend" circle="7"/>
	<KARMA spend="spell effect tests" circle="7"/>
	<DISCIPLINETALENT name="Orbiting Spy" circle="8"/>
	<SPELL name="Control Being" circle="8"/>
	<SPELL name="Globe of Silence" circle="8"/>
	<SPELL name="Horror Call" circle="8"/>
	<SPELL name="Netherblade" circle="8"/>
	<SPELL name="Restrain Horror" circle="8"/>
	<SPELL name="Shadow Tether" circle="8"/>
	<SPELL name="Translator Spirit" circle="8"/>
	<SPELL name="Visit Death" circle="8"/>
	<SPELL name="Wall of Bones" circle="8"/>
	<SPELL name="Wither Away" circle="8"/>
	<DEFENSE circle="8" kind="spell"/>
	<OPTIONALTALENT name="Animate Object" circle="9"/>
	<OPTIONALTALENT name="Armored Matrix" circle="9"/>
	<OPTIONALTALENT name="Armored Matrix" circle="9"/>
	<OPTIONALTALENT name="Atral Pocket" circle="9"/>
	<OPTIONALTALENT name="Cold Purify" circle="9"/>
	<OPTIONALTALENT name="Life Check" circle="9"/>
	<OPTIONALTALENT name="Matrix Strike" circle="9"/>
	<OPTIONALTALENT name="Steely Stare" circle="9"/>
	<DISCIPLINETALENT name="Bargain with Summoned Creatured" circle="9"/>
	<SPELL name="Create Life" circle="9"/>
	<SPELL name="Dark Sword" circle="9"/>
	<SPELL name="Disrupt Magic" circle="9"/>
	<SPELL name="Mystic Vessel" circle="9"/>
	<SPELL name="Shift Skin" circle="9"/>
	<SPELL name="Silent Darkness" circle="9"/>
	<SPELL name="Talent Shredder" circle="9"/>
	<SPELL name="Void Wave" circle="9"/>
	<SPELL name="Walking Dead" circle="9"/>
	<KARMA spend="Recovery Tests" circle="9"/>
	<ABILITY name="Otherworldly Control" circle="9"/>
	<DISCIPLINETALENT name="Summoning Circle" circle="10"/>
	<SPELL name="Animate Dead" circle="10"/>
	<SPELL name="Atrale Slice" circle="10"/>
	<SPELL name="Damage Transfer" circle="10"/>
	<SPELL name="Fragile Pattern" circle="10"/>
	<SPELL name="Gateway" circle="10"/>
	<SPELL name="Soul Trap" circle="10"/>
	<SPELL name="Spirit Tempest" circle="10"/>
	<SPELL name="Strong Pattern" circle="10"/>
	<SPELL name="Tap Horror Karma" circle="10"/>
	<DEFENSE circle="10" kind="spell"/>
	<KARMA spend="Action Tests made by a spirit or creature und his control" circle="10"/>
	<DISCIPLINETALENT name="Netherwalk" circle="11"/>
	<SPELL name="Alter Life" circle="11"/>
	<SPELL name="Shatter Pattern" circle="11"/>
	<SPELL name="Unnatural Life" circle="11"/>
	<DEFENSE circle="11" kind="social"/>
	<DEFENSE circle="11" kind="physical"/>
	<DISCIPLINETALENT name="Bone Compass" circle="12"/>
	<SPELL name="Forge Falsemen" circle="12"/>
	<SPELL name="Pervert Emotion" circle="12"/>
	<DEFENSE circle="12" kind="spell"/>
	<RECOVERYTEST circle="12"/>
	<OPTIONALTALENT name="Etherreal Weapon" circle="13"/>
	<OPTIONALTALENT name="Second Chance" circle="13"/>
	<OPTIONALTALENT name="Shared Matrix" circle="13"/>
	<OPTIONALTALENT name="Shared Matrix" circle="13"/>
	<OPTIONALTALENT name="Wound Transfer" circle="13"/>
	<DISCIPLINETALENT name="Spell Crystal Lock" circle="13"/>
	<SPELL name="Erease Horror Mark" circle="13"/>
	<SPELL name="Eternal Youth" circle="13"/>
	<DEFENSE circle="13" kind="social"/>
	<KARMASTEP circle="13"/>
	<ABILITY name="Astral Face" circle="13"/>
	<DISCIPLINETALENT name="Multi-Weaving" circle="14"/>
	<SPELL name="Call Foth the Army of Decay" circle="14"/>
	<DEFENSE circle="14" kind="spell"/>
	<RECOVERYTEST circle="14"/>
	<DISCIPLINETALENT name="Soul Shatter" circle="15"/>
	<DEFENSE circle="15" kind="social"/>
	<DEFENSE circle="15" kind="physical"/>
	<INITIATIVE circle="15"/>
	<INITIATIVE circle="15"/>
</DISCIPLINE>
