=== EriJan/Earthdawn-Character-Editor/config/earthdawncharacteristics.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/characteristics" xmlns="http://earthdawn.com/characteristics" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="CHARACTERISTICS_ENCUMBRANCE">
		<xs:attribute name="attribute" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="carrying" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_DEFENSERAITING">
		<xs:attribute name="attribute" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="defense" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_MYSTICARMOR">
		<xs:attribute name="attribute" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="armor" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_ATTRIBUTECOST">
		<xs:attribute name="modifier" type="xs:int" use="required"/>
		<xs:attribute name="cost" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_HEALTHRATING">
		<xs:attribute name="value" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="death" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="unconsciousness" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="wound" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="recovery" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_STEPDICETABLE">
		<xs:complexContent>
			<xs:extension base="edt:STEPDICE_type">
				<xs:attribute name="attribute" type="edt:unsigned_int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_COST">
		<xs:attribute name="cost" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_CIRCLE">
		<xs:sequence>
			<xs:element name="TALENTLPCOST" type="CHARACTERISTICS_COST" minOccurs="15" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_DISCIPLINENR">
		<xs:sequence>
			<xs:element name="CIRCLE" type="CHARACTERISTICS_CIRCLE" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="disciplinenr" type="edt:unsigned_int" use="required"/>
	</xs:complexType>
	<xs:complexType name="CHARACTERISTICS_LEGENDARYSTATUS">
		<xs:attribute name="circle" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="reown" type="edt:unsigned_int" use="required"/>
		<xs:attribute name="reputation" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="CHARACTERISTICS">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element maxOccurs="unbounded" minOccurs="1" name="ENCUMBRANCE" type="CHARACTERISTICS_ENCUMBRANCE"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="DEFENSERAITING" type="CHARACTERISTICS_DEFENSERAITING" />
				<xs:element maxOccurs="unbounded" minOccurs="1" name="MYSTICARMOR" type="CHARACTERISTICS_MYSTICARMOR"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="ATTRIBUTECOST" type="CHARACTERISTICS_ATTRIBUTECOST"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="HEALTHRATING" type="CHARACTERISTICS_HEALTHRATING"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="STEPDICETABLE" type="CHARACTERISTICS_STEPDICETABLE"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="DISCIPLINENR" type="CHARACTERISTICS_DISCIPLINENR"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="SKILLLPCOST" type="CHARACTERISTICS_COST"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="ATTRIBUTELPCOST" type="CHARACTERISTICS_COST"/>
				<xs:element maxOccurs="unbounded" minOccurs="1" name="LEGENDARYSTATUS" type="CHARACTERISTICS_LEGENDARYSTATUS"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/config/characteristics/ED4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<CHARACTERISTICS xmlns="http://earthdawn.com/characteristics" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:edt="http://earthdawn.com/datatypes" xsi:schemaLocation="http://earthdawn.com/characteristics ../earthdawncharacteristics.xsd">
  <ENCUMBRANCE attribute="0"  carrying="0"/>
  <ENCUMBRANCE attribute="1"  carrying="10"/>
  <ENCUMBRANCE attribute="2"  carrying="15"/>
  <ENCUMBRANCE attribute="3"  carrying="20"/>
  <ENCUMBRANCE attribute="4"  carrying="25"/>
  <ENCUMBRANCE attribute="5"  carrying="30"/>
  <ENCUMBRANCE attribute="6"  carrying="40"/>
  <ENCUMBRANCE attribute="7"  carrying="50"/>
  <ENCUMBRANCE attribute="8"  carrying="60"/>
  <ENCUMBRANCE attribute="9"  carrying="70"/>
  <ENCUMBRANCE attribute="10" carrying="80"/>
  <ENCUMBRANCE attribute="11" carrying="95"/>
  <ENCUMBRANCE attribute="12" carrying="110"/>
  <ENCUMBRANCE attribute="13" carrying="125"/>
  <ENCUMBRANCE attribute="14" carrying="140"/>
  <ENCUMBRANCE attribute="15" carrying="155"/>
  <ENCUMBRANCE attribute="16" carrying="175"/>
  <ENCUMBRANCE attribute="17" carrying="195"/>
  <ENCUMBRANCE attribute="18" carrying="215"/>
  <ENCUMBRANCE attribute="19" carrying="235"/>
  <ENCUMBRANCE attribute="20" carrying="255"/>
  <ENCUMBRANCE attribute="21" carrying="280"/>
  <ENCUMBRANCE attribute="22" carrying="305"/>
  <ENCUMBRANCE attribute="23" carrying="330"/>
  <ENCUMBRANCE attribute="24" carrying="355"/>
  <ENCUMBRANCE attribute="25" carrying="380"/>
  <ENCUMBRANCE attribute="26" carrying="410"/>
  <ENCUMBRANCE attribute="27" carrying="440"/>
  <ENCUMBRANCE attribute="28" carrying="470"/>
  <ENCUMBRANCE attribute="29" carrying="500"/>
  <ENCUMBRANCE attribute="30" carrying="530"/>
  <DEFENSERAITING attribute="0" defense="1" />
  <DEFENSERAITING attribute="1" defense="2" />
  <DEFENSERAITING attribute="3" defense="3" />
  <DEFENSERAITING attribute="5" defense="4" />
  <DEFENSERAITING attribute="7" defense="5" />
  <DEFENSERAITING attribute="9" defense="6" />
  <DEFENSERAITING attribute="11" defense="7" />
  <DEFENSERAITING attribute="13" defense="8" />
  <DEFENSERAITING attribute="15" defense="9" />
  <DEFENSERAITING attribute="17" defense="10" />
  <DEFENSERAITING attribute="19" defense="11" />
  <DEFENSERAITING attribute="21" defense="12" />
  <DEFENSERAITING attribute="23" defense="13" />
  <DEFENSERAITING attribute="25" defense="14" />
  <DEFENSERAITING attribute="27" defense="15" />
  <DEFENSERAITING attribute="28" defense="16" />
  <MYSTICARMOR attribute="0"  armor="0" />
  <MYSTICARMOR attribute="5"  armor="1" />
  <MYSTICARMOR attribute="10" armor="2" />
  <MYSTICARMOR attribute="15" armor="3" />
  <MYSTICARMOR attribute="20" armor="4" />
  <MYSTICARMOR attribute="25" armor="5" />
  <MYSTICARMOR attribute="30" armor="6" />
  <ATTRIBUTECOST modifier="-2" cost="-2" />
  <ATTRIBUTECOST modifier="-1" cost="-1" />
  <ATTRIBUTECOST modifier="0"  cost="0" />
  <ATTRIBUTECOST modifier="1"  cost="1" />
  <ATTRIBUTECOST modifier="2"  cost="2" />
  <ATTRIBUTECOST modifier="3"  cost="3" />
  <ATTRIBUTECOST modifier="4"  cost="5" />
  <ATTRIBUTECOST modifier="5"  cost="7" />
  <ATTRIBUTECOST modifier="6"  cost="9" />
  <ATTRIBUTECOST modifier="7"  cost="12" />
  <ATTRIBUTECOST modifier="8"  cost="15" />
  <HEALTHRATING  value="1" death="4"  unconsciousness="2"  wound="3"  recovery="1" />
  <HEALTHRATING  value="2" death="6"  unconsciousness="4"  wound="3"  recovery="1" />
  <HEALTHRATING  value="3" death="8"  unconsciousness="6"  wound="4"  recovery="1" />
  <HEALTHRATING  value="4" death="11" unconsciousness="8"  wound="4"  recovery="1" />
  <HEALTHRATING  value="5" death="13" unconsciousness="10" wound="5"  recovery="1" />
  <HEALTHRATING  value="6" death="15" unconsciousness="12" wound="5"  recovery="1" />
  <HEALTHRATING  value="7" death="18" unconsciousness="14" wound="6"  recovery="2" />
  <HEALTHRATING  value="8" death="20" unconsciousness="16" wound="6"  recovery="2" />
  <HEALTHRATING  value="9" death="22" unconsciousness="18" wound="7"  recovery="2" />
  <HEALTHRATING value="10" death="25" unconsciousness="20" wound="7"  recovery="2" />
  <HEALTHRATING value="11" death="27" unconsciousness="22" wound="8"  recovery="2" />
  <HEALTHRATING value="12" death="29" unconsciousness="24" wound="8"  recovery="2" />
  <HEALTHRATING value="13" death="32" unconsciousness="26" wound="9"  recovery="3" />
  <HEALTHRATING value="14" death="34" unconsciousness="28" wound="9"  recovery="3" />
  <HEALTHRATING value="15" death="36" unconsciousness="30" wound="10" recovery="3" />
  <HEALTHRATING value="16" death="39" unconsciousness="32" wound="10" recovery="3" />
  <HEALTHRATING value="17" death="41" unconsciousness="34" wound="11" recovery="3" />
  <HEALTHRATING value="18" death="43" unconsciousness="36" wound="11" recovery="3" />
  <HEALTHRATING value="19" death="46" unconsciousness="38" wound="12" recovery="4" />
  <HEALTHRATING value="20" death="48" unconsciousness="40" wound="12" recovery="4" />
  <HEALTHRATING value="21" death="50" unconsciousness="42" wound="13" recovery="4" />
  <HEALTHRATING value="22" death="53" unconsciousness="44" wound="13" recovery="4" />
  <HEALTHRATING value="23" death="55" unconsciousness="46" wound="14" recovery="4" />
  <HEALTHRATING value="24" death="57" unconsciousness="48" wound="14" recovery="4" />
  <HEALTHRATING value="25" death="60" unconsciousness="50" wound="15" recovery="5" />
  <HEALTHRATING value="26" death="62" unconsciousness="52" wound="15" recovery="5" />
  <HEALTHRATING value="27" death="64" unconsciousness="54" wound="16" recovery="5" />
  <HEALTHRATING value="28" death="67" unconsciousness="56" wound="16" recovery="5" />
  <HEALTHRATING value="29" death="69" unconsciousness="58" wound="17" recovery="5" />
  <HEALTHRATING value="30" death="71" unconsciousness="60" wound="17" recovery="5" />
  <STEPDICETABLE attribute="0"  step="1" dice="d4-2" />
  <STEPDICETABLE attribute="1"  step="2" dice="d4-1" />
  <STEPDICETABLE attribute="4"  step="3" dice="d4" />
  <STEPDICETABLE attribute="7"  step="4" dice="d6" />
  <STEPDICETABLE attribute="10" step="5" dice="d8" />
  <STEPDICETABLE attribute="13" step="6" dice="d10" />
  <STEPDICETABLE attribute="16" step="7" dice="d12" />
  <STEPDICETABLE attribute="19" step="8" dice="2d6" />
  <STEPDICETABLE attribute="22" step="9" dice="d8+d6" />
  <STEPDICETABLE attribute="25" step="10" dice="2d8" />
  <STEPDICETABLE attribute="28" step="11" dice="d10+d8" />
  <STEPDICETABLE attribute="31" step="12" dice="2d10" />
  <STEPDICETABLE attribute="34" step="13" dice="d12+d10" />
  <STEPDICETABLE attribute="37" step="14" dice="2d12" />
  <STEPDICETABLE attribute="40" step="15" dice="d12+2d6" />
  <STEPDICETABLE attribute="43" step="16" dice="d12+d8+d6" />
  <STEPDICETABLE attribute="46" step="17" dice="d12+2d8" />
  <STEPDICETABLE attribute="49" step="18" dice="d12+d10+d8" />
  <STEPDICETABLE attribute="52" step="19" dice="d20+2d6" />
  <STEPDICETABLE attribute="55" step="20" dice="d20+d8+d6" />
  <STEPDICETABLE attribute="58" step="21" dice="d20+2d8" />
  <STEPDICETABLE attribute="61" step="22" dice="d20+d10+d8" />
  <STEPDICETABLE attribute="64" step="23" dice="d20+2d10" />
  <STEPDICETABLE attribute="67" step="24" dice="d20+d12+d10" />
  <STEPDICETABLE attribute="70" step="25" dice="d20+2d12" />
  <STEPDICETABLE attribute="73" step="26" dice="d20+d12+2d6" />
  <STEPDICETABLE attribute="76" step="27" dice="d20+d12+d8+d6" />
  <STEPDICETABLE attribute="79" step="28" dice="d20+d12+2d8" />
  <STEPDICETABLE attribute="82" step="29" dice="d20+d12+d10+d8" />
  <STEPDICETABLE attribute="85" step="30" dice="2d20+2d6" />
  <STEPDICETABLE attribute="88" step="31" dice="2d20+d8+d6" />
  <STEPDICETABLE attribute="91" step="32" dice="2d20+2d8" />
  <STEPDICETABLE attribute="94" step="33" dice="2d20+d10+d8" />
  <STEPDICETABLE attribute="97" step="34" dice="2d20+2d10" />
  <STEPDICETABLE attribute="100" step="35" dice="2d20+d12+d10" />
  <STEPDICETABLE attribute="103" step="36" dice="2d20+2d12" />
  <STEPDICETABLE attribute="106" step="37" dice="2d20+d12+2d6" />
  <STEPDICETABLE attribute="109" step="38" dice="2d20+d12+d8+d6" />
  <STEPDICETABLE attribute="112" step="39" dice="2d20+d12+2d8" />
  <STEPDICETABLE attribute="115" step="40" dice="2d20+d12+d10+d8" />
	<DISCIPLINENR>
			<CIRCLE circle="0">
			<TALENTLPCOST cost="100"/>
			<TALENTLPCOST cost="200"/>
			<TALENTLPCOST cost="300"/>
			<TALENTLPCOST cost="500"/>
			<TALENTLPCOST cost="800"/>
			<TALENTLPCOST cost="1300"/>
			<TALENTLPCOST cost="2100"/>
			<TALENTLPCOST cost="3400"/>
			<TALENTLPCOST cost="5500"/>
			<TALENTLPCOST cost="8900"/>
			<TALENTLPCOST cost="14400"/>
			<TALENTLPCOST cost="23300"/>
			<TALENTLPCOST cost="37700"/>
			<TALENTLPCOST cost="61000"/>
			<TALENTLPCOST cost="98700"/>
		</CIRCLE>
		<CIRCLE circle="5">
			<TALENTLPCOST cost="200"/>
			<TALENTLPCOST cost="300"/>
			<TALENTLPCOST cost="500"/>
			<TALENTLPCOST cost="800"/>
			<TALENTLPCOST cost="1300"/>
			<TALENTLPCOST cost="2100"/>
			<TALENTLPCOST cost="3400"/>
			<TALENTLPCOST cost="5500"/>
			<TALENTLPCOST cost="8900"/>
			<TALENTLPCOST cost="14400"/>
			<TALENTLPCOST cost="23300"/>
			<TALENTLPCOST cost="37700"/>
			<TALENTLPCOST cost="61000"/>
			<TALENTLPCOST cost="98700"/>
			<TALENTLPCOST cost="159700"/>
		</CIRCLE>
		<CIRCLE circle="9">
			<TALENTLPCOST cost="300"/>
			<TALENTLPCOST cost="500"/>
			<TALENTLPCOST cost="800"/>
			<TALENTLPCOST cost="1300"/>
			<TALENTLPCOST cost="2100"/>
			<TALENTLPCOST cost="3400"/>
			<TALENTLPCOST cost="5500"/>
			<TALENTLPCOST cost="8900"/>
			<TALENTLPCOST cost="14400"/>
			<TALENTLPCOST cost="23300"/>
			<TALENTLPCOST cost="37700"/>
			<TALENTLPCOST cost="61000"/>
			<TALENTLPCOST cost="98700"/>
			<TALENTLPCOST cost="159700"/>
			<TALENTLPCOST cost="258400"/>
		</CIRCLE>
		<CIRCLE circle="13">
			<TALENTLPCOST cost="500"/>
			<TALENTLPCOST cost="800"/>
			<TALENTLPCOST cost="1300"/>
			<TALENTLPCOST cost="2100"/>
