=== EriJan/Earthdawn-Character-Editor/config/eceguilayout.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://earthdawn.com/eceguilayout" xmlns="http://earthdawn.com/eceguilayout" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:edt="http://earthdawn.com/datatypes">
	<xs:import namespace="http://earthdawn.com/datatypes" schemaLocation="earthdawndatatypes.xsd"/>
	<xs:complexType name="LAYOUT_DIMENSION_type">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="X" type="LAYOUT_SIZES_type"/>
			<xs:element minOccurs="0" maxOccurs="1" name="Y" type="LAYOUT_SIZES_type"/>
			<xs:element minOccurs="0" maxOccurs="1" name="Z" type="LAYOUT_SIZES_type"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LAYOUT_TABLE_type">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="COLUMN" type="LAYOUT_SIZES_type"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="LAYOUT_SIZES_type">
		<xs:attribute name="min" type="edt:unsigned_int" use="optional"/>
		<xs:attribute name="preferred" type="edt:unsigned_int" use="optional"/>
		<xs:attribute name="max" type="edt:unsigned_int" use="optional"/>
	</xs:complexType>
	<xs:element name="ECEGUILAYOUT">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" name="MAINWINDOW" type="LAYOUT_DIMENSION_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="STATUSWINDOW" type="LAYOUT_DIMENSION_type"/>
				<xs:element minOccurs="1" maxOccurs="1" name="TABWINDOW" type="LAYOUT_DIMENSION_type"/>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="TABLE" type="LAYOUT_TABLE_type" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== EriJan/Earthdawn-Character-Editor/config/eceguilayout.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ECEGUILAYOUT xmlns="http://earthdawn.com/eceguilayout" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://earthdawn.com/eceguilayout eceguilayout.xsd">
	<MAINWINDOW x="1020" y="740"/>
	<TABLE name="spellselection">
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  0 -->
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  1 -->
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  2 -->
		<COLUMN min="50"  preferred="70"  max="120"/> <!--  3 -->
		<COLUMN min="100" preferred="300" max="1000"/><!--  4 -->
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  5 -->
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  6 -->
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  7 -->
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  8 -->
		<COLUMN min="100" preferred="300" max="1000"/><!--  9 -->
		<COLUMN min="100" preferred="300" max="1000"/><!-- 10 -->
		<COLUMN min="50"  preferred="70"  max="120"/> <!-- 11 -->
		<COLUMN min="50"  preferred="70"  max="120"/> <!-- 12 -->
	</TABLE>
	<TABLE name="talentselection">
		<COLUMN min="20"  preferred="50"  max="30"/>  <!--  0 -->
	</TABLE>
</ECEGUILAYOUT>
